(()=>{'use strict';
const M=window.GenbaMass125,KEY='genba-fabrication125';
const E=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e};
const field=(label,control)=>{const e=E('label',label);e.append(control);return e};
const inp=(type,value)=>{const e=E('input');e.type=type;e.value=value??'';if(type==='number'){e.step='any';e.inputMode='decimal'}return e};
const btn=(s,f)=>{const e=E('button',s);e.type='button';e.addEventListener('click',f);return e};
const sel=(options,value)=>{const e=E('select');options.forEach(([v,n])=>{const o=E('option',n);o.value=v;e.append(o)});e.value=value;return e};
const number=s=>s.trim()===''?null:Number(s);
const download=(name,value,type)=>{const u=URL.createObjectURL(new Blob([value],{type})),a=E('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)};
const blank=()=>({name:'',material:'',density:null,quantity:1,confirmed:false,notes:'',components:[{name:'',operation:'add',shape:'box',count:1,values:[null,null,null],points:[]}]});
document.addEventListener('DOMContentLoaded',()=>{
let data={format:'genba-mass',version:1,units:'mm',title:'',notes:'',parts:[blank()]},pending=null,last='',photoUrl=null;
const s=E('section');s.id='fabricationMass125';s.className='card fab125';s.append(E('h2','🏗️ 製缶品・複雑形状の重量計算'),E('p','各自のChatGPTで図面を整理 → データをここへ取り込む → 寸法を確認・修正 → 重量計算。アプリはAIに接続せず、入力・写真・保存はこの端末で処理します。自動読取りはこの画面では行いません。'));
const help=E('details');help.append(E('summary','初めて使う方へ：ChatGPTへの依頼文'));
help.append(E('p','下の依頼文をコピーし、ご自身のChatGPTに図面写真と一緒に送ってください。返されたJSONを貼り付けるか、JSONファイルを選びます。料金・回数制限は各自のChatGPT契約に従います。社外に出せない図面は送らないでください。'));
const prompt=E('textarea');prompt.readOnly=true;prompt.rows=10;
prompt.value=`添付の機械・製缶図面から重量計算の内訳を作ってください。部材を重ならない形状に分け、穴・切欠きを差し引きます。不明な寸法・材質・密度・数量は推測せずnullにし、notesに質問を残してください。投影図の同一部材を二重計上しないこと。計算対象にできない部材も省略せず、未確認の部材として残してください。画像の長さから寸法を推定しないでください。密度が参考値なら明記してください。\n次のJSON形式で返してください。コード以外の説明はJSON外に記載。\n${JSON.stringify(M.example,null,2)}\nこれは形式例です。例の値は実際の図面の値に置換してください。ルートformat=genba-mass、version=1、units=mm。partsは部材、quantityは部材数、densityはg/cm3。各componentsのcountは部材1個当たりの同一形状数。operationはadd/subtract。confirmedはfalse。\n対応shapeとvaluesの順序：\n${Object.entries(M.shapes).map(([k,v])=>k+': '+v[1].join(', ')).join('\n')}\npolygonはさらにpoints:[[x,y],...]（mm、周囲順、始点を重複させない、自己交差なし）。sectionは規格から確認したkg/mを使い出典をnotesに書く。massは既知重量kg。曲げ板・ホッパーは板厚中心の展開面積areaを使い、未知ならnull。frustumは中実の体積なので薄板ホッパーの外形へそのまま使わない。角パイプはメーカー単位質量sectionを優先。notesに省略部位、ねじ・溶接金属・付属品の扱いと不確実な点を明記。`;
const copyStatus=E('p');help.append(prompt,btn('依頼文をコピー',async()=>{try{await navigator.clipboard.writeText(prompt.value);copyStatus.textContent='コピーしました。ご自身のChatGPTへ貼り付けてください。'}catch(e){prompt.focus();prompt.select();copyStatus.textContent='依頼文を長押ししてコピーしてください。'}}),copyStatus);s.append(help);
const io=E('details');io.open=true;io.append(E('summary','① データ取込み（未確認として取り込みます）'));const paste=E('textarea');paste.rows=6;paste.placeholder='ChatGPTが作成したJSONをここに貼り付け';const file=inp('file','');file.accept='.json,application/json';const status=E('p');status.setAttribute('aria-live','polite');const preview=E('div');const apply=btn('このデータに切り替える',()=>{if(!pending)return;data=pending;pending=null;apply.disabled=true;paste.value='';file.value='';render();preview.replaceChildren();status.textContent='取り込みました。全ての部材を図面と照合して確認済みにしてください。'});apply.disabled=true;
function stage(raw){pending=null;apply.disabled=true;preview.replaceChildren();try{if(raw.length>1000000)throw Error('データは1MB以下');raw=raw.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');pending=M.normalize(JSON.parse(raw));preview.append(E('p','案件：'+(pending.title||'名称なし')+'／部材'+pending.parts.length+'件'),E('p',pending.notes));try{M.calculate(pending,false);preview.append(E('p','数値形式は計算可能です。読取りの正しさは図面と確認してください。'))}catch(e){preview.append(E('p','要確認：'+e.message+'。取込み後に修正できます。'))}status.textContent='現在の入力を置き換えます。残す場合は先にJSONを書き出してください。';apply.disabled=false}catch(e){status.textContent='取り込めません：'+e.message}}
paste.addEventListener('input',()=>{pending=null;apply.disabled=true;preview.replaceChildren();status.textContent='編集した内容を再度確認してください。'});
let readToken=0;file.addEventListener('change',async()=>{const token=++readToken;pending=null;apply.disabled=true;const f=file.files?.[0];if(!f)return;if(f.size>1000000){status.textContent='1MB以下のJSONファイルを選んでください';return}try{const raw=await f.text();if(token===readToken)stage(raw)}catch(e){status.textContent='ファイルを読めませんでした'}});
io.append(field('JSONファイル',file),field('またはJSONを貼り付け',paste),btn('貼り付け内容を確認',()=>{readToken++;stage(paste.value)}),btn('練習用架台をプレビュー',()=>{readToken++;stage(JSON.stringify(M.example))}),status,preview,apply);s.append(io);
const photo=E('details');photo.append(E('summary','図面写真を手元に表示（保存・送信しません）'));const pf=inp('file','');pf.accept='image/*';const pv=E('div');pv.className='fabPhoto125';const img=E('img');img.alt='重量計算の参照図面';const pstatus=E('p'),zoom=inp('range',100);zoom.min=100;zoom.max=400;zoom.step=25;zoom.addEventListener('input',()=>img.style.width=zoom.value+'%');img.addEventListener('error',()=>pstatus.textContent='画像を表示できません。JPEG/PNGで選び直してください。');pf.addEventListener('change',()=>{if(photoUrl)URL.revokeObjectURL(photoUrl);const f=pf.files?.[0];if(!f){img.removeAttribute('src');return}photoUrl=URL.createObjectURL(f);img.src=photoUrl;zoom.value=100;img.style.width='100%';pstatus.textContent='写真は再読込時に消えます。'});pv.append(img);photo.append(field('写真選択',pf),field('拡大率',zoom),pstatus,pv);s.append(photo);
const title=inp('text',''),notes=E('textarea');notes.rows=3;const parts=E('div'),result=E('div');result.className='fabResult125';result.setAttribute('aria-live','polite');
function invalid(){last='';result.replaceChildren(E('p','編集後は確認済みにチェックして、再計算してください。'))}
title.addEventListener('input',()=>{data.title=title.value;invalid()});notes.addEventListener('input',()=>{data.notes=notes.value;invalid()});
s.append(E('h3','② 部材・形状を照合して修正'),field('案件名・図番',title),field('全体の注記・省略した部品・未確認事項',notes),E('p','部材の数量×部材1個の内訳で合計します。形状の個数と部材数量を二重に増やさないでください。異なる材質は別部材に分けます。曲げ板・ホッパーは板厚中心の展開面積を入力。形鋼は実際の規格のkg/mを入力します。'),parts,btn('部材を追加',()=>{if(data.parts.length>=100){result.textContent='部材は100件まで';return}data.parts.push(blank());render()}));
function render(){title.value=data.title;notes.value=data.notes;parts.replaceChildren();invalid();data.parts.forEach((p,pi)=>{
const article=E('details');article.className='fabPart125';article.open=data.parts.length<5;const summary=E('summary','部材'+(pi+1)+'：'+(p.name||'名称未入力'));article.append(summary);
const checked=inp('checkbox','');checked.checked=p.confirmed;function edit(){p.confirmed=false;checked.checked=false;invalid()}
function bind(obj,key,labelText,type='text'){const i=inp(type,obj[key]);i.addEventListener('input',()=>{obj[key]=type==='number'?number(i.value):i.value;edit();if(key==='name'&&obj===p)summary.textContent='部材'+(pi+1)+'：'+(p.name||'名称未入力')});article.append(field(labelText,i));return i}
bind(p,'name','部材名');bind(p,'material','材質・形鋼の規格');bind(p,'density','密度 g/cm³（体積計算には必須）','number');bind(p,'quantity','この部材の数量','number');bind(p,'notes','注記・不明点・単位質量の出典');
p.components.forEach((c,ci)=>{const row=E('div');row.className='fabComponent125';row.append(E('h4','形状'+(ci+1)));const n=inp('text',c.name);n.addEventListener('input',()=>{c.name=n.value;edit()});row.append(field('部分名',n));const op=sel([['add','＋ 外形・部材'],['subtract','− 穴・切欠き']],c.operation);op.addEventListener('change',()=>{c.operation=op.value;edit()});row.append(field('足す／引く',op));const shape=sel(Object.entries(M.shapes).map(([k,v])=>[k,v[0]]),c.shape);shape.addEventListener('change',()=>{c.shape=shape.value;c.values=M.shapes[c.shape][1].map(()=>null);c.points=[];edit();render()});row.append(field('形状',shape));M.shapes[c.shape][1].forEach((lab,vi)=>{const i=inp('number',c.values[vi]);i.addEventListener('input',()=>{c.values[vi]=number(i.value);edit()});row.append(field(lab+(['section','mass','area'].includes(c.shape)?'':' mm'),i))});
if(c.shape==='polygon'){const pts=E('textarea');pts.rows=5;pts.value=c.points.map(pt=>pt.map(n=>n??'').join(',')).join('\n');pts.placeholder='0,0\n100,0\n100,50\n0,50';pts.addEventListener('input',()=>{c.points=pts.value.trim().split('\n').filter(x=>x.trim()).map(l=>{const v=l.split(',');return v.length===2?v.map(x=>number(x.trim())):[null,null]});edit()});row.append(field('周囲順の頂点 x,y（mm／1行1点）',pts))}
const count=inp('number',c.count);count.step=1;count.addEventListener('input',()=>{c.count=number(count.value);edit()});row.append(field('部材1個あたりの同じ形状の数',count),btn('形状を削除',()=>{if(p.components.length===1){result.textContent='部材には形状を1つ以上残してください';return}p.components.splice(ci,1);edit();render()}));article.append(row)});
article.append(btn('この部材に穴・形状を追加',()=>{if(p.components.length>=100)return;p.components.push(blank().components[0]);edit();render()}));checked.addEventListener('change',()=>{p.confirmed=checked.checked;invalid()});article.append(field('寸法・材質・数量・控除の重なり・注記を図面と確認した',checked),btn('この部材を削除',()=>{if(!confirm('部材「'+(p.name||'名称なし')+'」を削除しますか？'))return;data.parts.splice(pi,1);render()}));parts.append(article)
})}
const calculate=btn('③ 確認済み部材の重量を計算',()=>{try{const answer=M.calculate(data);result.replaceChildren(E('h3','合計 '+answer.total.toLocaleString('ja-JP',{maximumSignificantDigits:8})+' kg（概算）'));const lines=['製缶品重量 内訳',data.title,data.notes,''];answer.parts.forEach((p,i)=>{result.append(E('p',(p.name||'部材'+(i+1))+'：'+p.one.toFixed(6)+' kg × '+p.quantity+' ＝ '+p.total.toFixed(6)+' kg'));lines.push(`${i+1}. ${p.name} [${p.material}] 密度=${data.parts[i].density??'不使用'} g/cm3\n数量=${p.quantity}、1個=${p.one.toPrecision(8)}kg、合計=${p.total.toPrecision(8)}kg\n注記：${data.parts[i].notes}`);p.components.forEach((c,j)=>{const src=data.parts[i].components[j];lines.push(`  ${c.operation==='subtract'?'−':'＋'} ${c.name||M.shapes[src.shape][0]}：${c.kg.toPrecision(8)}kg／${c.formula}／values=${JSON.stringify(src.values)}／個数=${src.count}`);if(src.shape==='polygon')lines.push('  頂点mm='+JSON.stringify(src.points))})});lines.push('\n総重量：'+answer.total.toPrecision(8)+'kg','理論計算。重なり・省略部品・溶接金属・公差は自動補正なし。吊り作業用の実重量・重心の確認とは別。');last=lines.join('\n')}catch(e){invalid();result.textContent='計算できません：'+e.message}});
s.append(calculate,result,btn('計算内訳を保存（テキスト）',()=>{if(!last){result.textContent='先に計算してください';return}download('fabrication-weight.txt',last,'text/plain;charset=utf-8')}));
const saveStatus=E('p');saveStatus.setAttribute('aria-live','polite');
function serialized(){return JSON.stringify(M.normalize(data),null,2)}
s.append(E('h3','④ 保存・再利用'),btn('入力をJSONファイルに書き出す',()=>{try{download('fabrication-weight.json',serialized(),'application/json');saveStatus.textContent='取込み可能なJSONを書き出しました。写真は含みません。'}catch(e){saveStatus.textContent=e.message}}),btn('この端末に下書き保存',()=>{try{localStorage.setItem(KEY,serialized());saveStatus.textContent='このブラウザに保存しました。写真は含みません。ブラウザのデータ削除で消えるため、JSONも保存してください。'}catch(e){saveStatus.textContent='保存できません：'+e.message}}),btn('端末の下書きをプレビュー',()=>{try{const raw=localStorage.getItem(KEY);if(!raw){saveStatus.textContent='下書きがありません';return}stage(raw);io.open=true;io.scrollIntoView({block:'start'});}catch(e){saveStatus.textContent='下書きを読めません'}}),saveStatus,E('p','ファイルは公開GitHubへアップロードしないでください。書き出し先は端末の保存・共有画面で確認してください。この計算は寸法の対応、部材の不足、重なり、単位質量の正しさを自動判定しません。'),E('p','角パイプの角Rや形鋼のフィレットを単純な角断面に置き換えると誤差が出ます。規格表のkg/mを使うか、省略した形状を注記してください。溶接金属・ボルト等は別部材として追加できます。薄板曲面は展開面積、鋳物等の複雑な自由曲面はCAD体積や既知重量を使ってください。'));
render();document.getElementById('material60').before(s);
});
})();
