(()=>{'use strict';
const rad=x=>x*Math.PI/180,ok=(...v)=>v.every(Number.isFinite);
function dimensions(mode,m,z1,z2,beta=0,alpha=20){
 const b=mode==='spur'?0:beta;
 if(!ok(m,z1,z2,b,alpha)||m<=0||!Number.isInteger(z1)||!Number.isInteger(z2)||z1<3||z2<3||alpha<=0||alpha>=45||b<0||b>=60||!['spur','normal','transverse'].includes(mode))throw Error('モジュールは正数、歯数は3以上の整数、圧力角は0°超45°未満、ねじれ角は0°以上60°未満で入力してください。');
 const mn=mode==='normal'?m:m*Math.cos(rad(b)),mt=mode==='normal'?m/Math.cos(rad(b)):m;
 const an=mode==='transverse'?Math.atan(Math.tan(rad(alpha))*Math.cos(rad(b))):rad(alpha),at=Math.atan(Math.tan(an)/Math.cos(rad(b)));
 const d1=mt*z1,d2=mt*z2;
 return {mn,mt,an:an*180/Math.PI,at:at*180/Math.PI,d1,d2,da1:d1+2*m,da2:d2+2*m,df1:d1-2.5*m,df2:d2-2.5*m,pn:Math.PI*mn,pt:Math.PI*mt,a:(d1+d2)/2,ratio:z2/z1,travel:Math.PI*d1,small:z1<17||z2<17};
}
function estimate(da,z){if(!ok(da,z)||da<=0||!Number.isInteger(z)||z<3)throw Error('外径は正数、歯数は3以上の整数を入力してください。');return da/(z+2)}
function backlash(values,basis,r,dp,alpha,lo,hi){
 if(!values.length||!values.every(x=>Number.isFinite(x)&&x>=0)||!ok(alpha,lo,hi)||alpha<=0||alpha>=45||lo<0||hi<lo||!['tangent','normal','radius'].includes(basis))throw Error('測定値は0以上、指定下限・上限は0以上で下限≦上限、かみ合い圧力角は0°超45°未満にしてください。');
 if(basis==='radius'&&(!ok(r,dp)||r<=0||dp<=0))throw Error('測定半径と作動ピッチ円直径は正数で入力してください。');
 const jt=values.map(x=>basis==='normal'?x/Math.cos(rad(alpha)):basis==='radius'?x*dp/(2*r):x),jn=jt.map(x=>x*Math.cos(rad(alpha)));
 return {jt,jn,min:Math.min(...jn),max:Math.max(...jn),outside:jn.filter(x=>x<lo-1e-10||x>hi+1e-10).length};
}
const presets=[{key:'ss1',model:'SS1-30',m:1,lo:.08,hi:.18,page:110},{key:'ss2',model:'SS2-30',m:2,lo:.12,hi:.26,page:118},{key:'ss3',model:'SS3-30',m:3,lo:.14,hi:.32,page:122},{key:'ss5',model:'SS5-30',m:5,lo:.20,hi:.44,page:126}];
const types=[
['spur','平歯車／スパーギヤ','平行軸','spur 平歯車 スパー ピニオン','歯すじが軸に平行。基本的な回転伝達で、寸法を理解しやすい形式。理想的な歯面力では軸方向の推力は生じない。','搬送、送り、一般減速機。外歯同士は互いに逆回転。','高速域の音・振動、歯面摩耗、軸の平行度を確認。モジュールと圧力角が合っても強度・歯幅・精度の確認が必要。'],
['helical','はすば歯車／ヘリカルギヤ','平行軸','helical はすば ヘリカル ねじれ スラスト','歯すじを斜めにして、かみ合いが徐々に移る。平歯車より滑らかな運転を狙えるが、軸方向の推力が発生する。','モーター減速機、ピニオンスタンドなど。平行軸の外歯対は通常、同じねじれ角の右ねじれと左ねじれを組にする。','歯直角モジュールmnと正面モジュールmtを区別。スラストを受ける軸受・位置決めと歯当たりを確認。'],
['double','やまば・ダブルヘリカル','平行軸','herringbone やまば ダブルヘリカル','左右逆のねじれを組み合わせる。左右の荷重が釣り合う条件で軸方向推力を相殺する構成。','大きな動力を扱う駆動装置。中央に逃げ溝がある形式・連続したV形の形式がある。','左右の歯面荷重が不均等なら推力や片当たりが残る。片側だけの歯当たりでは判断しない。'],
['internal','内歯車／インターナルギヤ','平行軸','internal 内歯 リングギヤ','リングの内側に歯がある。内歯と外歯が固定軸でかみ合う場合は同方向に回る。','遊星機構のリングなど。標準・無転位では中心距離はm×(内歯数−外歯数)/2。','歯数差・組付け方法によって干渉が起こり得る。外歯用の歯先径式や組合せ条件を流用しない。'],
['rack','ラック＆ピニオン','回転↔直線','rack ラック ピニオン 直線送り CP','直線状のラックと円形ピニオンで、回転運動と直線運動を変換する。','送り装置・位置決め。標準平歯の1回転移動量はπ×m×z。','長尺ラックの継ぎ目、取付高さ、平行度、歯当たりを確認。CPは円ピッチそのものを表すので、mの数値と混同しない。'],
['bevel','すぐばかさ歯車／ベベル','交差軸','bevel ベベル かさ すぐば マイタ','円すい面に歯を持ち、軸線が交差する方向へ回転を伝える。マイタは一般に歯数比1のかさ歯車対。','直角方向の駆動など。軸角は設計で決まり、必ず90°とは限らない。','組付け距離・軸角・歯当たりを同時に管理。バックラッシュだけを合わせて取付け距離を崩さない。'],
['spiral','まがりばかさ歯車','交差軸','spiral bevel スパイラルベベル まがりば','曲線状の歯すじで滑らかなかみ合いを狙うかさ歯車。回転方向や歯すじで推力の方向も変わる。','高速の直角駆動など。対として選定し、メーカーの組付け条件を使う。','駆動側・反駆動側の歯当たり、軸受の予圧、取付け距離を確認。平歯車の軸間調整を流用しない。'],
['hypoid','ハイポイドギヤ','食い違い軸','hypoid ハイポイド オフセット','軸線が交わらずオフセットしたかさ歯車に似た構成。歯面にすべりが伴う。','車両の終減速機など。潤滑油と歯当たり調整を機種の仕様に合わせる。','かさ歯車との見た目だけの互換判断は不可。対の識別、取付け距離、指定油を確認。'],
['screw','ねじ歯車／スクリューギヤ','食い違い軸','screw クロスヘリカル ねじ歯車','交わらない軸間ではすば歯車をかみ合わせる形式。歯面の接触とすべりに注意する。','小動力の方向変換、計器・軽負荷の送りなど。','平行軸ヘリカルの相手条件を流用しない。軸角、ねじれ方向・角度、潤滑、許容荷重を確認。'],
['worm','ウォーム＆ウォームホイール','食い違い軸','worm ウォーム 条数 セルフロック','ねじ状のウォームとホイールで、大きい減速比を1段で得やすい。減速比＝ホイール歯数/ウォーム条数。','減速機・位置決め。すべりによる発熱・効率・潤滑が重要。','セルフロックを確実な保持機能として決めつけない。1条・多条、歯形、相手材質、指定油を確認。'],
['planet','遊星歯車機構','機構の分類','planetary 遊星 太陽 サン リング キャリア','太陽歯車・遊星歯車・内歯車・キャリアを組み合わせる。同軸でコンパクトに減速する機構。','サーボ減速機など。歯の種類ではなく組合せ機構で、固定・入力・出力の部材により速度比が変わる。','リング固定・太陽入力・キャリア出力ならi＝1＋Zr/Zs。これを別の固定条件に流用しない。']
];
window.GenbaGears128={dimensions,estimate,backlash,presets,types};
const svg=(label,body)=>`<svg viewBox="0 0 600 260" role="img" aria-label="${label}"><g font-family="sans-serif" font-size="18" fill="#183a50">${body}</g></svg>`;
function wheel(cx,cy,r,n=12){let points=[];for(let i=0;i<n*4;i++){const a=i*Math.PI/(n*2),rr=i%4===1||i%4===2?r:r-7;points.push(`${cx+rr*Math.cos(a)},${cy+rr*Math.sin(a)}`)}return `<polygon points="${points.join(' ')}" fill="#bedbeb" stroke="#22658d" stroke-width="2"/><circle cx="${cx}" cy="${cy}" r="9" fill="white" stroke="#22658d"/>`}
function icon(kind){
 if(['helical','double','screw'].includes(kind)){let lines='';for(let x=105;x<460;x+=45)lines+=`<path d="${kind==='double'?`M${x} 65l35 65 -35 65`:`M${x} 65l65 130`}" fill="none" stroke="#276891" stroke-width="6"/>`;return svg('歯すじの模式図',`<rect x="85" y="60" width="430" height="140" rx="20" fill="#d9eaf5" stroke="#276891"/>${lines}<text x="85" y="235">歯すじ：${kind==='double'?'左右逆のねじれ':'斜め'}</text><path d="M40 130H560" stroke="#6f8595" stroke-dasharray="5 5"/>`)}
 if(kind==='rack'){let p='M50 200';for(let x=50;x<530;x+=40)p+=`H${x+8}l8 -16h12l8 16`;return svg('ラックとピニオンの模式図',`${wheel(290,110,70)}<path d="${p}V230H50Z" fill="#cbe3f3" stroke="#22658d"/><text x="40" y="45">回転↔直線移動</text><text x="430" y="170">ラック</text>`)}
 if(kind==='hypoid')return svg('ハイポイドの軸オフセットを示す配置図',`<path d="M55 150H295M395 60V225" stroke="#6d8394" stroke-width="3" stroke-dasharray="6 5"/><path d="M145 110L265 150 145 190Z" fill="#bedbeb" stroke="#22658d" stroke-width="3"/><ellipse cx="395" cy="150" rx="52" ry="88" fill="#dceaf4" stroke="#22658d" stroke-width="3"/><text x="40" y="30">軸が交わらないオフセット配置（配置模式図）</text><text x="40" y="240">歯形・接触位置は実物図ではありません</text>`);
 if(['bevel','spiral'].includes(kind))return svg('かさ歯車と軸位置の模式図',`<path d="M50 145H260L410 50M260 145L410 240" stroke="#6d8394" stroke-dasharray="6 5" fill="none"/><path d="M130 95L260 145 130 195Z M290 75L260 145 365 135Z" fill="#bedbeb" stroke="#22658d" stroke-width="3"/><text x="40" y="35">円すい状の歯車（模式図）</text><text x="40" y="235">${kind==='hypoid'?'ハイポイドは軸線が交わらない':'交差軸：軸線の交点を基準に組付け'}</text>${kind==='hypoid'?'<path d="M400 85V205" stroke="#cb6a24" stroke-width="3"/>':''}`);
 if(kind==='worm')return svg('ねじ状のウォームとホイールの模式図',`${wheel(355,160,75)}<rect x="65" y="55" width="430" height="48" fill="#cbe3f3" stroke="#22658d"/>${[95,150,205,260,315,370,425].map(x=>`<path d="M${x} 55l30 48" stroke="#22658d" stroke-width="4"/>`).join('')}<text x="70" y="35">ウォーム（条数を確認）</text><text x="65" y="210">ホイール →</text>`);
 if(kind==='internal'||kind==='planet')return svg('内歯車と遊星機構の配置模式図',`<circle cx="300" cy="130" r="110" fill="#bedbeb" stroke="#22658d"/><circle cx="300" cy="130" r="93" fill="white" stroke="#22658d" stroke-dasharray="9 5"/>${kind==='internal'?wheel(340,170,40):wheel(300,130,30)+wheel(300,68,30)+wheel(246,161,30)+wheel(354,161,30)}<text x="35" y="30">リング内側に歯</text><text x="20" y="245">${kind==='planet'?'中心：太陽／周囲：遊星／遊星を支持：キャリア':'内歯と外歯は固定軸なら同方向'}</text>`);
 return svg('平歯車対の模式図',`${wheel(200,125,65)}${wheel(350,125,85,16)}<path d="M200 125H350" stroke="#6d8394" stroke-dasharray="5 5"/><text x="150" y="235">外歯対：互いに逆回転</text><text x="40" y="35">図の歯形は模式表現（インボリュート原図ではない）</text>`);
}
const diameterDiagram=svg('歯先円、基準円、歯底円の違い',`${wheel(155,130,105,18)}<circle cx="155" cy="130" r="92" fill="none" stroke="#ce782b" stroke-width="3" stroke-dasharray="7 5"/><circle cx="155" cy="130" r="82" fill="none" stroke="#448253" stroke-width="2"/><path d="M155 24H400 M220 64H400 M229 171H400" stroke="#5c7486"/><text x="410" y="30">歯先円 da</text><text x="410" y="70">基準円 d＝m z</text><text x="410" y="180">歯底円 df</text><text x="300" y="225">基準円は仮想の円</text>`);
const gaugeDiagram=svg('歯車を固定し相手を軽く往復、測定子を円周接線方向へ当てる',`${wheel(350,150,80)}<circle cx="105" cy="70" r="27" fill="white" stroke="#2c668c" stroke-width="3"/><path d="M132 70H350" fill="none" stroke="#2c668c" stroke-width="5"/><path d="M105 70l12 -12M350 150V70" stroke="#ce6b2b" stroke-width="3"/><text x="35" y="30">相手歯車を固定し、測る側だけ軽く往復</text><text x="45" y="125">測定子の方向：接線 →</text><text x="445" y="100">測定半径 r</text><text x="300" y="245">歯面直角 jn ≠ 円周 jt</text>`);
document.addEventListener('DOMContentLoaded',()=>{
const s=document.createElement('section');s.id='gears128';s.className='card gears128';
s.innerHTML=`<h2>⚙️ ギヤ・歯車｜種類・モジュール・バックラッシュ</h2>
<p>種類を選ぶ → 寸法を読む → 組合せ・歯当たりを確認 → バックラッシュを測る、をまとめました。バックラッシュは「バックラッシ」とも呼びます。</p>
<div class="gearTopics128"><button type="button" data-topic="types128">種類・特徴</button><button type="button" data-topic="module128">モジュール・寸法</button><button type="button" data-topic="lash128">バックラッシュ</button><button type="button" data-topic="assembly128">組立・不具合</button></div>
<h3 id="types128">1．ギヤの種類と使い分け</h3><label>種類・用語検索<input type="search" id="gearSearch128" placeholder="例：はすば、ウォーム、スラスト、遊星"></label><button type="button" id="gearClear128">検索をクリア</button><p id="gearCount128" role="status" aria-live="polite"></p><div id="gearCards128"></div>
<h3 id="module128">2．モジュールを詳しく理解する</h3>${diameterDiagram}
<details open><summary>m・歯数・ピッチ・圧力角の関係</summary><p>モジュールmは歯の大きさを表す長さ（mm）。平歯車ではm＝基準円直径d/歯数z、円ピッチp＝πm。m2なら歯の繰返し間隔pは約6.283 mmです。歯数が同じならmが大きいほど歯車も大きくなりますが、強度は材質・歯幅・熱処理・荷重なども含めて判断します。</p><p>基準円はノギスで直接測る外面ではありません。標準・無転位の外歯平歯車では、歯先径da＝m(z＋2)、歯底径df≈m(z−2.5)、標準中心距離a＝m(z1＋z2)/2。歯底形状は工具や切下げなどの影響を受けます。</p><p>圧力角αは力の向きに関係する角度で、歯すじのねじれ角βとは別です。標準品には20°が多く見られますが、既設品は図面・型式で確認します。同じmでも圧力角・歯形・ねじれ条件が違えば、そのまま相手になりません。</p><p>はすばは歯直角mnと正面mtを区別：mt＝mn/cosβ、d＝mt z＝mn z/cosβ。歯直角圧力角αnと正面αtはtanαt＝tanαn/cosβ。図面に「m2」とだけある場合は、どちらの基準か確認します。</p><p>DP（ダイヤメトラルピッチ）はインチ系の大きさの表現でm＝25.4/DP。CPは円ピッチ（mm）でm＝CP/π。モジュールの数値と同一として扱わないでください。</p></details>
<details><summary>歯形・転位・切下げ</summary><p>一般的なインボリュート歯形は、かみ合い中の回転比を一定にする歯形です。歯車の転位は歯切り工具を基準位置からずらし、歯厚・歯先径・中心距離などを調整する設計です。</p><p>外径からm＝da/(z＋2)で推定できるのは標準・無転位の外歯平歯車に限ります。転位、歯先修整、摩耗、はすば、かさ歯車ではこの推定を流用しないでください。確定にはまたぎ歯厚・オーバピン寸法・歯形測定や元図面を使います。</p><p>歯数が少ない標準歯車では歯元が削られる「切下げ」が問題になります。20°の標準歯形では17歯付近が確認目安ですが、工具・転位などで条件が変わります。歯数だけで使用可否を決めません。</p></details>
<h4>標準・無転位の外歯対：寸法計算</h4>
<div class="gearGrid128"><label>歯車基準<select id="gearMode128"><option value="spur">平歯車：m・α</option><option value="normal">平行軸はすば：mn・αn</option><option value="transverse">平行軸はすば：mt・αt</option></select></label><label>モジュール<input id="gearM128" type="number" value="2" step="any" inputmode="decimal"></label><label>駆動側歯数 z1<input id="gearZ1128" type="number" value="20" step="1" inputmode="numeric"></label><label>従動側歯数 z2<input id="gearZ2128" type="number" value="40" step="1" inputmode="numeric"></label><label>入力基準の圧力角 α（°）<input id="gearAlpha128" type="number" value="20" step="any" inputmode="decimal"></label><label>ねじれ角 β（°・平歯車では無視）<input id="gearBeta128" type="number" value="20" step="any" inputmode="decimal"></label></div>
<button type="button" id="gearCalc128">寸法を計算</button><div id="gearOut128" class="gearResult128" aria-live="polite"></div>
<p>計算対象：同じ基準モジュール・圧力角、無転位・標準歯たけの外歯対。歯たけは選択した基準で歯末たけ＝入力m、全歯たけ＝2.25×入力mとしています。内歯・かさ・ウォーム・転位歯車・特殊歯形の寸法は対象外です。数値は強度やかみ合い干渉の合否を判定しません。</p>
<details><summary>外径と歯数からmを推定（標準平歯車限定）</summary><div class="gearGrid128"><label>歯先の外径 da（mm）<input id="gearDa128" type="number" value="64" step="any"></label><label>歯数 z<input id="gearZe128" type="number" value="30" step="1"></label></div><button type="button" id="gearEstimate128">参考モジュールを計算</button><p id="gearEstimateOut128" aria-live="polite"></p></details>
<h3 id="lash128">3．バックラッシュの値と測り方</h3>${gaugeDiagram}
<p>バックラッシュは、相手歯車を固定して反対側を少し往復させたときの歯面間の遊びです。歯先と歯底の半径方向の隙間（頂げき）とは別です。</p>
<details open><summary>推奨値の決め方：設備指定を優先</summary><p>まず設備図面・減速機メーカーの指定値を使います。次に歯車の型式、歯数対、中心距離、温度、荷重、歯幅、潤滑、測定方向を確認します。モジュールだけから全設備に共通の推奨値を出すことはできません。</p><p>下表は、<b>KHK SS平歯車の確認できたカタログ例</b>です。同じ型式同士のかみ合いに対する<b>歯面直角方向jnの理論値</b>であり、一般設備の調整推奨値や摩耗限界ではありません。実機の中心距離・偏心・組立で変わります。</p><div class="gearTable128"><table><thead><tr><th>同型式同士の例</th><th>m</th><th>jn（mm）</th><th>カタログ頁</th></tr></thead><tbody>${presets.map(p=>`<tr><td>${p.model} × ${p.model}</td><td>${p.m}</td><td>${p.lo.toFixed(2)}～${p.hi.toFixed(2)}</td><td>${p.page}</td></tr>`).join('')}</tbody></table></div><p><a target="_blank" rel="noopener" href="https://khkgears.net/pdf/ss.pdf">KHK SS寸法表</a>／<a target="_blank" rel="noopener" href="https://khkgears.net/pdf/spur-tech.pdf">表の適用条件（法線方向・同型式対）</a>。平歯車のjnを円周方向jtに直す場合、jt＝jn/cosαw（αwは作動圧力角）。標準中心距離の20°ならjn 0.12はjt約0.128 mmです。</p><p>通常の歯車対を無条件にゼロへ調整すると、局部的な詰まりや温度変化などで問題になります。低バックラッシュ専用機構は、予圧・負荷・寿命を含むメーカー手順で扱います。</p></details>
<details open><summary>現場での測定手順</summary><ol><li>設備を停止・無動力にし、測定対象以外が動かない状態を確保。相手歯車を固定します。</li><li>ダイヤルを安定した基準へ固定。測る歯車の歯・測定治具へ、円周の接線方向に測定子を当てます。歯面に直角に当てる方法と混同しません。</li><li>歯を押しつけ過ぎず、左右の歯面が軽く接するまで往復。指示差を読む。軸受の遊び・キーのがた・固定側の動きが混ざっていないか確認します。</li><li>角度位置を変えて一周を確認し、各位置の値と最小・最大を残す。4点入力は例で、必要な測定点数は設備仕様で決めます。</li><li>指定値と同じ方向・同じピッチ円位置へ換算して比較。歯当たりと回転の重さも確認します。</li></ol><p>測定半径rが作動ピッチ半径rwと違う場合、接線方向の小変位はjt≈指示差×rw/r。これは微小角の近似で、斜め当ての補正や治具のたわみは含みません。減速機の出力軸の総合遊びは、単一歯車対の値とは分けて記録します。</p></details>
<h4>平歯車：測定値の換算と指定範囲との比較</h4><p>円周値jt・歯面直角値jnを換算し、<b>jnで入力した指定範囲</b>と比較します。はすば・かさ・ウォームの換算はこの画面の対象外です。</p>
<div class="gearGrid128"><label>比較基準<select id="lashPreset128"><option value="custom">設備指定を手入力</option>${presets.map(p=>`<option value="${p.key}">参考例：${p.model}同士</option>`).join('')}</select></label><label>測定値の方向<select id="lashBasis128"><option value="tangent">作動ピッチ円の円周方向 jt</option><option value="normal">歯面直角方向 jn</option><option value="radius">任意半径の接線方向の指示差</option></select></label><label>作動圧力角 αw（°）<input id="lashAlpha128" type="number" value="20" step="any"></label><label>測定半径 r（mm・任意半径の場合）<input id="lashR128" type="number" value="30" step="any"></label><label>作動ピッチ円直径 dw（mm・任意半径の場合）<input id="lashDp128" type="number" value="60" step="any"></label><label>指定下限 jn（mm）<input id="lashLo128" type="number" step="any" placeholder="設備指定値"></label><label>指定上限 jn（mm）<input id="lashHi128" type="number" step="any" placeholder="設備指定値"></label></div>
<label>各位置の測定値（mm・改行またはカンマで区切る）<textarea id="lashValues128" rows="4" placeholder="0.14&#10;0.16&#10;0.15&#10;0.17"></textarea></label><button type="button" id="lashCalc128">換算して指定範囲と比較</button><div id="lashOut128" class="gearResult128" aria-live="polite">設備指定値と測定値を入力してください。</div>
<details><summary>小さくしたいとき・大きいとき</summary><p>標準外歯平歯車の近似では、中心距離変化Δaによる円周バックラッシュ変化Δjt≈2Δa tanαw。軸間を広げると増える方向ですが、歯当たり・かみ合い率も変わるため、この式だけで移動量を決めません。</p><p>かさ・ハイポイドは取付け距離と歯当たり、ウォームは対の形式や軸方向調整機構を確認。軸受・キー・固定部のがた、偏心、摩耗も調べてから歯車位置を調整します。</p></details>
<h3 id="assembly128">4．組立・点検で見るところ</h3><details open><summary>組み込み前→組み込み後の確認</summary><ol><li>対の型式・m基準・圧力角・歯数・転位・ねじれ方向・材質・熱処理を照合。</li><li>軸・穴のはめあい、キー、基準面、軸受、中心距離・軸角を確認。圧入・焼きばめでは歯面を押さず、ハブの支持と温度条件を設計手順に合わせる。</li><li>歯当たり確認材を薄く使い、指定条件で両回転方向の当たりを見る。端だけの当たりは軸の傾き、片寄りなどを切り分ける。</li><li>一周のバックラッシュと振れを確認。小さい場所だけをゼロにしない。</li><li>指定油・油量・供給方法、ガードを確認し、設備の試運転手順に従って音・振動・温度を記録。</li></ol></details>
<details><summary>異常の例と確認先</summary><div class="gearTable128"><table><thead><tr><th>症状</th><th>確認する事項</th></tr></thead><tbody><tr><td>一周の一部だけ重い</td><td>偏心、歯面の傷、異物、軸曲がり、最小バックラッシュ</td></tr><tr><td>歯幅の端だけ当たる</td><td>軸平行度、取付け面、軸受、荷重時のたわみ</td></tr><tr><td>正逆でがた・衝撃</td><td>バックラッシュ、キー・継手・軸受の遊び、制御の加減速</td></tr><tr><td>歯面に小穴・剥離</td><td>ピッチング等の損傷、荷重履歴、歯当たり、潤滑</td></tr><tr><td>すり傷・焼付き・発熱</td><td>給油、指定粘度、温度、過負荷、異物</td></tr><tr><td>歯元の亀裂・歯欠け</td><td>衝撃、過負荷、材料・熱処理、歯元応力。欠損品の運転継続は設備手順で判断</td></tr></tbody></table></div><p>症状だけで原因を確定せず、いつ・どの回転数・どちらの回転方向・負荷条件で出たか記録します。</p></details>
<details><summary>材料・加工・精度の見方</summary><p>炭素鋼は一般用途、合金鋼の浸炭焼入れなどは歯面硬さと内部の靭性を狙います。高周波焼入れ、調質、歯研の有無で同じmでも性能が変わります。樹脂品は軽量・低騒音を狙えますが、温度・吸水・寸法変化・荷重条件を確認します。</p><p>歯車精度の等級は規格名と規格年・評価項目まで読む必要があります。旧規格と現行の表記を数字だけで比較しません。強度には歯元の曲げと歯面の面圧の両方があり、寸法計算の結果から許容トルクを推定しないでください。</p></details>
<details><summary>出典・収録条件</summary><ul><li><a href="https://www.khkgears.co.jp/gear_technology/basic_guide/khk347/" target="_blank" rel="noopener">KHK：歯車の種類</a></li><li><a href="https://www.endo-kogyo.co.jp/japanese/blog/haguruma.html" target="_blank" rel="noopener">遠藤工業：歯車の種類と特徴</a></li><li><a href="https://www.khkgears.co.jp/gear_technology/basic_guide/khk357_2/" target="_blank" rel="noopener">KHK：平歯車の寸法計算</a></li><li><a href="https://www.khkgears.co.jp/gear_technology/basic_guide/khk365/" target="_blank" rel="noopener">KHK：はすば歯車の寸法計算</a></li><li><a href="https://www.khkgears.co.jp/gear_technology/intermediate_guide/khk406_2/" target="_blank" rel="noopener">KHK：バックラッシの定義</a></li><li><a href="https://www.khkgears.co.jp/gear_technology/faq/" target="_blank" rel="noopener">KHK：組立・ウォーム等のQ＆A</a></li></ul><p>資料確認：2026-10-07。図は本アプリ独自の模式図です。カタログ参考値と設備の指定値を区別して使ってください。検索・計算は端末内で動作し、出典リンクを開く場合のみ通信します。</p></details>`;
(document.getElementById('material60')||document.body.lastElementChild).before(s);
const $=id=>s.querySelector('#'+id),num=id=>$(id).value.trim()===''?NaN:Number($(id).value),f=x=>x.toFixed(3);
function showTypes(){const q=$('gearSearch128').value.normalize('NFKC').toLowerCase().trim(),out=types.filter(v=>v.join(' ').normalize('NFKC').toLowerCase().includes(q));$('gearCards128').replaceChildren();for(const t of out){const d=document.createElement('details');d.innerHTML=`<summary>${t[1]}｜${t[2]}</summary>${icon(t[0])}<p><b>特徴：</b>${t[4]}</p><p><b>用途・構成：</b>${t[5]}</p><p><b>組立で確認：</b>${t[6]}</p>`;$('gearCards128').append(d)}$('gearCount128').textContent=out.length?`${out.length}種類表示／${types.length}種類`:'該当する項目がありません。別の用語で検索してください。'}
$('gearSearch128').addEventListener('input',showTypes);$('gearClear128').addEventListener('click',()=>{$('gearSearch128').value='';showTypes()});showTypes();
s.querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.topic).scrollIntoView({block:'start',behavior:'smooth'})));
function calc(){try{const mode=$('gearMode128').value,x=dimensions(mode,num('gearM128'),num('gearZ1128'),num('gearZ2128'),num('gearBeta128'),num('gearAlpha128'));$('gearOut128').textContent=`mn＝${f(x.mn)} / mt＝${f(x.mt)} mm\n圧力角 αn＝${f(x.an)}° / αt＝${f(x.at)}°\n基準円直径 d1＝${f(x.d1)} / d2＝${f(x.d2)} mm\n歯先径 da1＝${f(x.da1)} / da2＝${f(x.da2)} mm\n標準歯底径の参考 df1＝${f(x.df1)} / df2＝${f(x.df2)} mm\n標準中心距離 a＝${f(x.a)} mm\n円ピッチ pn＝${f(x.pn)} / pt＝${f(x.pt)} mm\n歯数比 z2/z1＝${f(x.ratio)}（外歯対は逆回転）\n${mode==='spur'?`平歯ラックで駆動側1回転の移動量＝${f(x.travel)} mm\n`:''}${x.small?'少歯数です。切下げ・干渉の検討が必要です。\n':''}強度・許容トルク・干渉の合否は判定していません。`;}catch(e){$('gearOut128').textContent=e.message}}
$('gearCalc128').addEventListener('click',calc);calc();
$('gearEstimate128').addEventListener('click',()=>{try{$('gearEstimateOut128').textContent=`参考m＝${f(estimate(num('gearDa128'),num('gearZe128')))} mm。標準・無転位の平歯車であることを確認し、図面や歯形測定で確定してください。`;}catch(e){$('gearEstimateOut128').textContent=e.message}});
$('lashPreset128').addEventListener('change',()=>{const p=presets.find(x=>x.key===$('lashPreset128').value);$('lashLo128').value=p?String(p.lo):'';$('lashHi128').value=p?String(p.hi):'';if(p)$('lashAlpha128').value='20';$('lashOut128').textContent=p?'参考値を入力しました。同型式対・標準組付けでの例です。測定条件を確認してから比較してください。':'設備の指定範囲をjnで入力してください。'});
$('lashCalc128').addEventListener('click',()=>{try{const raw=$('lashValues128').value.trim();if(!raw)throw Error('各位置の測定値を入力してください。');const tokens=raw.split(/[\s,、;]+/);if(tokens.length>1000)throw Error('測定値は1000点以内にしてください。');const values=tokens.map(Number),x=backlash(values,$('lashBasis128').value,num('lashR128'),num('lashDp128'),num('lashAlpha128'),num('lashLo128'),num('lashHi128'));$('lashOut128').textContent=x.jn.map((v,i)=>`${i+1}点目：jt ${f(x.jt[i])} / jn ${f(v)} mm`).join('\n')+`\njn最小＝${f(x.min)} / 最大＝${f(x.max)} mm\n指定範囲から外れる点：${x.outside} / ${values.length}点\n${x.outside?'範囲外の位置と測定条件を確認してください。':'入力した全点が指定範囲内です。'}\n歯当たり・温度・一周の未測定位置・設備全体の合否は別途確認してください。`;}catch(e){$('lashOut128').textContent=e.message}});
for(const id of ['gearMode128','gearM128','gearZ1128','gearZ2128','gearAlpha128','gearBeta128'])$(id).addEventListener('input',()=>{$('gearOut128').textContent='入力を変更しました。「寸法を計算」を押してください。'});
for(const id of ['lashBasis128','lashR128','lashDp128','lashAlpha128','lashLo128','lashHi128','lashValues128'])$(id).addEventListener('input',()=>{$('lashOut128').textContent='入力を変更しました。「換算して指定範囲と比較」を押してください。'});
});})();
