/* All dimensions mm; density g/cm3; outputs kg. No network or evaluation of imported code. */
(function(root){'use strict';
const shapes={box:['角板・角柱',['幅','高さ','長さ']],cylinder:['円柱・丸穴',['直径','長さ／深さ']],tube:['リング・丸パイプ',['外径','内径','長さ']],triangle:['三角板・三角柱',['底辺','高さ','板厚／長さ']],trapezoid:['台形板',['上底','下底','高さ','板厚']],area:['展開面積から（曲げ板・ホッパー等）',['展開面積 mm²','板厚']],polygon:['多角形板（頂点座標）',['板厚']],frustum:['円すい台（中実）',['大径','小径（円すいは0）','高さ']],section:['形鋼の単位質量',['単位質量 kg/m','切断長さ mm']],mass:['重量を直接加算',['重量 kg']]};
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
function text(x,max=500){if(typeof x!=='string'||x.length>max)throw Error('文字列の形式・長さが不正');return x}
function num(x){if(x===null)return null;if(typeof x!=='number'||!Number.isFinite(x)||Math.abs(x)>1e12)throw Error('数値は有限の数、未確認はnullにしてください');return x}
function normalize(raw){if(!raw||raw.format!=='genba-mass'||raw.version!==1||raw.units!=='mm')throw Error('genba-mass形式・version 1・units mmのデータが必要です');if(!Array.isArray(raw.parts)||raw.parts.length<1||raw.parts.length>100)throw Error('部材数は1～100');let total=0;return {format:'genba-mass',version:1,units:'mm',title:text(raw.title??''),notes:text(raw.notes??'',3000),parts:raw.parts.map(p=>{if(!p||!Array.isArray(p.components)||p.components.length<1||p.components.length>100||(total+=p.components.length)>1000)throw Error('形状数は各部材1～100、全体1000以下');return {name:text(p.name??''),material:text(p.material??''),density:num(p.density??null),quantity:num(p.quantity??null),confirmed:false,notes:text(p.notes??'',2000),components:p.components.map(c=>{if(!c||!own(shapes,c.shape)||!['add','subtract'].includes(c.operation)||!Array.isArray(c.values)||c.values.length!==shapes[c.shape][1].length)throw Error('形状・加減算・寸法欄の数が不正');let points=[];if(c.shape==='polygon'){if(!Array.isArray(c.points)||c.points.length>100)throw Error('多角形の頂点は100以下');points=c.points.map(pt=>{if(!Array.isArray(pt)||pt.length!==2)throw Error('頂点は[x,y]');return pt.map(num)})}return {name:text(c.name??''),shape:c.shape,operation:c.operation,count:num(c.count??null),values:c.values.map(num),points}})}})} }
function polygonArea(pts){if(pts.length<3)throw Error('多角形は周囲順に3点以上');pts.forEach(p=>p.forEach(n=>{if(!Number.isFinite(n))throw Error('頂点座標を入力')}));const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);const on=(a,b,c)=>cross(a,b,c)===0&&c[0]>=Math.min(a[0],b[0])&&c[0]<=Math.max(a[0],b[0])&&c[1]>=Math.min(a[1],b[1])&&c[1]<=Math.max(a[1],b[1]);const intersect=(a,b,c,d)=>{let x=cross(a,b,c),y=cross(a,b,d),z=cross(c,d,a),w=cross(c,d,b);return (x*y<0&&z*w<0)||on(a,b,c)||on(a,b,d)||on(c,d,a)||on(c,d,b)};for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length];if(a[0]===b[0]&&a[1]===b[1])throw Error('同じ頂点が連続しています');for(let j=i+1;j<pts.length;j++){if(j===i+1||(i===0&&j===pts.length-1))continue;if(intersect(a,b,pts[j],pts[(j+1)%pts.length]))throw Error('多角形が交差・接触しています。周囲順の座標を確認')}}let area=Math.abs(pts.reduce((sum,p,i)=>{const q=pts[(i+1)%pts.length];return sum+p[0]*q[1]-q[0]*p[1]},0))/2;if(area<=0)throw Error('多角形の面積が0');return area}
function component(c,density){if(!own(shapes,c.shape))throw Error('形状が不正');if(!['add','subtract'].includes(c.operation))throw Error('加減算を確認');if(!Number.isInteger(c.count)||c.count<1)throw Error('形状個数は1以上の整数');const v=c.values;if(v.length!==shapes[c.shape][1].length||v.some((n,i)=>!Number.isFinite(n)||(c.shape==='frustum'&&i===1?n<0:n<=0)))throw Error('寸法・重量を正の数で入力（円すいの小径のみ0可）');let volume=null,kg=0,formula='';switch(c.shape){case'box':volume=v[0]*v[1]*v[2];formula='幅×高さ×長さ';break;case'cylinder':volume=Math.PI*v[0]**2*v[1]/4;formula='π×直径²×長さ÷4';break;case'tube':if(v[0]<=v[1])throw Error('外径は内径より大きく');volume=Math.PI*(v[0]**2-v[1]**2)*v[2]/4;formula='π×(外径²−内径²)×長さ÷4';break;case'triangle':volume=v[0]*v[1]*v[2]/2;formula='底辺×高さ×板厚÷2';break;case'trapezoid':volume=(v[0]+v[1])*v[2]*v[3]/2;formula='(上底＋下底)×高さ×板厚÷2';break;case'area':volume=v[0]*v[1];formula='展開面積×板厚';break;case'polygon':volume=polygonArea(c.points)*v[0];formula='頂点座標による面積×板厚';break;case'frustum':if(v[0]<=v[1])throw Error('大径は小径より大きく');volume=Math.PI*v[2]*(v[0]**2+v[0]*v[1]+v[1]**2)/12;formula='π×高さ×(大径²＋大径×小径＋小径²)÷12';break;case'section':kg=v[0]*v[1]/1000;formula='単位質量kg/m×長さmm÷1000';break;case'mass':kg=v[0];formula='指定重量kg';}
if(volume!==null){if(!Number.isFinite(density)||density<=0)throw Error('密度g/cm³を入力');kg=volume*density/1e6;formula+='×密度÷1,000,000'}kg*=c.count;if(!Number.isFinite(kg)||kg<=0)throw Error('計算範囲外');return {kg,volume:volume===null?null:volume*c.count,formula}}
function calculate(data,requireConfirmed=true){let sum=0;const parts=data.parts.map((p,i)=>{if(requireConfirmed&&!p.confirmed)throw Error('部材'+(i+1)+'：図面と照合して確認済みにしてください');if(!Number.isInteger(p.quantity)||p.quantity<1)throw Error('部材'+(i+1)+'：数量は1以上の整数');let one=0,plus=0,minus=0;const components=p.components.map((c,j)=>{let x;try{x=component(c,p.density)}catch(e){throw Error('部材'+(i+1)+'／形状'+(j+1)+'：'+e.message)}if(c.operation==='subtract'){one-=x.kg;minus+=x.kg}else{one+=x.kg;plus+=x.kg}return {...x,name:c.name,operation:c.operation}});if(!Number.isFinite(one)||one<=0)throw Error('部材'+(i+1)+'：残る重量が0以下です');const total=one*p.quantity;if(!Number.isFinite(total))throw Error('計算範囲外');sum+=total;return {name:p.name,material:p.material,quantity:p.quantity,one,total,plus,minus,components}});if(!parts.length||!Number.isFinite(sum)||sum<=0)throw Error('計算対象を確認');return {parts,total:sum}}
const example={format:'genba-mass',version:1,units:'mm',title:'練習用架台（寸法例）',notes:'板・脚・リブのみの例。締結品と溶接金属は含めていません。',parts:[{name:'天板',material:'一般鋼（密度は概算）',density:7.85,quantity:1,confirmed:false,notes:'200×100×10、直径10の貫通穴4個',components:[{name:'板',shape:'box',operation:'add',count:1,values:[200,100,10]},{name:'穴',shape:'cylinder',operation:'subtract',count:4,values:[10,10]}]},{name:'脚',material:'形鋼：単位質量を仮定',density:null,quantity:4,confirmed:false,notes:'2kg/mは練習値。実際の規格値に置換。',components:[{name:'脚',shape:'section',operation:'add',count:1,values:[2,500]}]},{name:'補強リブ',material:'一般鋼（概算）',density:7.85,quantity:4,confirmed:false,notes:'直角三角形',components:[{name:'リブ',shape:'triangle',operation:'add',count:1,values:[50,50,6]}]}]};
root.GenbaMass125={shapes,normalize,polygonArea,component,calculate,example};
})(typeof window!=='undefined'?window:globalThis);
