(()=>{'use strict';
const rad=d=>d*Math.PI/180,deg=r=>r*180/Math.PI;
const finite=(...a)=>a.every(Number.isFinite);
function line(rA,rB,gA,gB,L){if(!finite(rA,rB,gA,gB,L)||L<=0)throw Error('読み・目標値は有限の数値、測点間距離Lは正数で入力してください。');const eA=gA-rA,eB=gB-rB;return {eA,eB,delta:eB-eA,angle:deg(Math.atan2(eB-eA,L)),slope:(eB-eA)/L*1000,moveA:-eA,moveB:-eB};}
function trig(distance,angle,mode,convention,i,t,h){const a=convention==='zenith'?90-angle:angle;if(!finite(distance,angle,i,t,h)||distance<=0||i<0||t<0||Math.abs(a)>=90||!['horizontal','slant'].includes(mode)||!['elevation','zenith'].includes(convention))throw Error('距離は正数、器械高・目標高は0以上。仰俯角は−90°超90°未満（天頂角は0°超180°未満）で入力してください。');const D=mode==='horizontal'?distance:distance*Math.cos(rad(a)),v=mode==='horizontal'?distance*Math.tan(rad(a)):distance*Math.sin(rad(a));return {a,D,v,dh:i+v-t,height:h+i+v-t};}
function dms(d,m,s,sign){if(!finite(d,m,s)||d<0||!Number.isInteger(d)||!Number.isInteger(m)||m<0||m>=60||s<0||s>=60||![1,-1].includes(sign))throw Error('度は0以上の整数、分は0～59の整数、秒は0以上60未満にしてください。');const angle=sign*(d+m/60+s/3600);if(Math.abs(angle)>=90)throw Error('この換算計算は角度の絶対値90°未満を対象にします。');return {angle,radian:rad(angle),perM:1000*Math.tan(rad(angle))};}
function level(h,bs,points,target){if(!finite(h,bs,target)||bs<0||!points.length||points.length>50||points.some(p=>!p.name||!Number.isFinite(p.fs)||p.fs<0))throw Error('高さと読みを数値で入力してください。測点は1～50点、前視の読みは0以上にしてください。');const hi=h+bs;return {hi,points:points.map(p=>({...p,dh:bs-p.fs,height:hi-p.fs,move:target-(hi-p.fs),targetReading:hi-target}))};}
function peg(ma,mb,na,nb,da,db){if(!finite(ma,mb,na,nb,da,db)||Math.min(ma,mb,na,nb)<0||da<=0||db<=0||Math.abs(da-db)<1)throw Error('読みは0以上、距離は正数で入力し、近点・遠点の距離差は1 mm以上にしてください。');const dh=ma-mb,expectedB=na-dh,discrepancy=nb-expectedB,eps=((na-nb)-dh)/(da-db);return {dh,expectedB,discrepancy,per10m:eps*10000};}
function project(S,a){if(!finite(S,a)||S<=0||Math.abs(a)>90)throw Error('斜距離は正数、角度は−90°～90°で入力してください。');return {D:S*Math.cos(rad(a)),v:S*Math.sin(rad(a))};}
window.GenbaSurvey130={line,trig,dms,level,peg,project};
const fmt=(v,n=3)=>(Math.abs(v)<.5*Math.pow(10,-n)?0:v).toFixed(n);
const svg=(label,body,h=330)=>`<svg viewBox="0 0 560 ${h}" role="img" aria-label="${label}"><rect width="560" height="${h}" rx="12" fill="#f2f8fc"/><g stroke="#28678c" stroke-width="3" fill="none">${body}</g></svg>`;
const txt=(x,y,t)=>`<text x="${x}" y="${y}" stroke="none" fill="#183d54" font-size="21">${t}</text>`;
const transitDiagram=()=>svg('トランシットの望遠鏡・水平回転軸・整準台・三脚と視準線',`<path d="M75 285L130 175L185 285 M130 175V290 M92 174H168 M105 150H155V174H105Z M100 80H175V115H100Z M120 115V150 M145 115V150"/><circle cx="175" cy="97" r="18" fill="#d7edfb"/><path d="M194 97H520" stroke-dasharray="8 5"/>${txt(35,45,'望遠鏡・十字線')}${txt(275,82,'視準線（見ている線）')}${txt(220,150,'水平・鉛直の回転と目盛')}${txt(220,196,'整準ねじ・気泡管')}${txt(220,245,'三脚：振動・沈みを抑える')}${txt(35,322,'構成模式図（形状は機種で異なる）')}`);
const planDiagram=()=>svg('上面図。器械Oから基準方向Aと別の方向Bを見て水平角を測る',`<circle cx="95" cy="225" r="18" fill="#d7edfb"/><path d="M113 225H505 M107 211L425 60 M190 225A95 95 0 0 0 179 183"/><circle cx="480" cy="225" r="7" fill="#28678c"/><circle cx="425" cy="60" r="7" fill="#28678c"/>${txt(43,273,'器械 O')}${txt(300,265,'A：基準方向 0°')}${txt(270,48,'B：測る方向')}${txt(193,203,'水平角 β')}${txt(28,316,'平面上での角度。高低差は別に測る')}`);
const scaleDiagram=()=>svg('上面図。AとBのスケールを同じ向きに置き視準線の読みを比較する。目盛りの増える向きがプラスY',`<path d="M50 175H525" stroke-dasharray="8 5"/><circle cx="68" cy="175" r="12" fill="#28678c"/><path d="M215 65V268 M445 65V268 M205 90H225 M205 120H225 M205 150H225 M205 180H225 M205 210H225 M205 240H225 M435 90H455 M435 120H455 M435 150H455 M435 180H455 M435 210H455 M435 240H455 M215 295H445 M215 287V303 M445 287V303 M510 150V80"/><polygon points="510,70 500,90 520,90" fill="#28678c"/>${txt(182,40,'A 手前')}${txt(407,40,'B 奥')}${txt(30,145,'視準線')}${txt(233,200,'読み rA')}${txt(458,200,'rB')}${txt(302,322,'L')}${txt(464,58,'＋Y')}${txt(30,250,'両方とも')}${txt(30,278,'上へ目盛増')}`);
const elevationDiagram=()=>svg('側面図。水平距離D、仰俯角α、器械高i、目標高tによる高低差',`<path d="M40 270H535 M70 180H505" stroke-dasharray="7 5"/><path d="M70 180L495 80 M70 180V270 M495 80V200 M465 200H530 M120 180A50 50 0 0 0 119 168 M70 300H495"/><circle cx="70" cy="180" r="9" fill="#28678c"/><circle cx="495" cy="80" r="8" fill="#28678c"/>${txt(25,225,'i')}${txt(508,145,'t')}${txt(135,173,'α')}${txt(230,125,'斜距離 S')}${txt(224,324,'水平距離 D')}${txt(33,261,'A')}${txt(450,231,'B')}${txt(260,53,'目標の中心')}`);
const levelDiagram=()=>svg('水平な視準線から標尺の読みを比較。Aの後視よりBの前視が小さければBが高い',`<path d="M45 95H520" stroke-dasharray="8 5"/><path d="M75 45V270 M465 45V220 M45 270H120 M435 220H515 M240 82H302V104H240Z M272 104V170 M272 170L225 290 M272 170L318 290 M272 170V290 M85 95V270 M475 95V220"/><path d="M65 65H85 M65 95H85 M65 125H85 M65 155H85 M65 185H85 M65 215H85 M65 245H85 M455 65H475 M455 95H475 M455 125H475 M455 155H475 M455 185H475"/>${txt(132,65,'水平視準線 HI')}${txt(92,145,'後視 BS')}${txt(343,145,'前視 FS')}${txt(38,315,'A 基準点')}${txt(417,260,'B 測点')}${txt(153,325,'Bは高い → 読みは小さい')}`);
const pegDiagram=()=>svg('二点法。まずAとBの中間、次にA寄りから両方を読む',`<path d="M60 80V260 M495 80V260 M60 200H495" stroke-dasharray="8 5"/><circle cx="278" cy="200" r="14" fill="#28678c"/><circle cx="120" cy="200" r="14" fill="#e9ae42"/><path d="M60 285H495 M60 277V293 M495 277V293"/>${txt(43,62,'A')}${txt(478,62,'B')}${txt(226,150,'① 中間据え')}${txt(70,245,'② A寄り')}${txt(85,315,'①は等距離。②は距離差を記録')}`);
const laserDiagram=type=>type==='distance'?svg('レーザー距離計の測定基準面から対象物までの距離を測る',`<rect x="75" y="130" width="90" height="65" rx="10" fill="#d7edfb"/><path d="M165 155H485" stroke="#dc493a"/><path d="M485 60V270 M75 205V270 M75 250H485 M165 115V220" stroke-dasharray="6 4"/>${txt(36,85,'後端基準の例')}${txt(197,135,'レーザー')}${txt(290,278,'測定距離')}${txt(438,47,'対象面')}${txt(32,320,'前端・後端・三脚基準を設定で確認')}`):type==='line'?svg('ラインレーザーで壁や床に水平線と鉛直線を作る',`<rect x="150" y="50" width="360" height="230" fill="#eef3f6"/><path d="M180 165H485 M330 65V265" stroke="#409953"/><rect x="35" y="170" width="60" height="60" rx="8" fill="#d7edfb"/><path d="M95 195L180 165 M95 195L330 65 M95 195L330 265" stroke="#409953" stroke-dasharray="5 5"/>${txt(280,42,'鉛直ライン')}${txt(350,155,'水平ライン')}${txt(30,305,'線の中心を読む。線幅＝測定精度ではない')}`):type==='rotary'?svg('回転レーザーは水平なレーザー面を作り受光器で高さを読む',`<ellipse cx="270" cy="150" rx="230" ry="55" stroke="#dc493a" stroke-dasharray="8 5"/><path d="M270 150V220 M270 220L230 295 M270 220L310 295 M270 220V295 M465 75V285"/><rect x="445" y="125" width="40" height="60" fill="#d7edfb"/><circle cx="270" cy="150" r="18" fill="#d7edfb"/>${txt(130,50,'水平な基準面（模式図）')}${txt(355,222,'受光器・ロッド')}${txt(40,320,'受光器の中心・感度・固定位置を確認')}`):type==='plumb'?svg('ポイントレーザーの上下点で鉛直位置を移す',`<path d="M55 65H515 M55 280H515 M275 65V280" stroke-dasharray="7 5"/><rect x="248" y="158" width="54" height="55" fill="#d7edfb"/><path d="M275 65V158 M275 213V280" stroke="#409953"/><circle cx="275" cy="65" r="7" fill="#409953"/><circle cx="275" cy="280" r="7" fill="#409953"/>${txt(312,73,'上点・天井')}${txt(312,285,'下点・床')}${txt(42,320,'鉛直の転写。高さや距離の数値とは別')}`):type==='shaft'?svg('軸芯出し用レーザー。二つの軸に測定ヘッドを固定して回転位置ごとに測る',`<rect x="40" y="160" width="170" height="80" fill="#d7edfb"/><rect x="340" y="160" width="175" height="80" fill="#d7edfb"/><path d="M130 160V275 M425 160V275 M210 180H260 M300 180H340"/><rect x="245" y="160" width="70" height="40"/><rect x="205" y="85" width="45" height="45" fill="#d7edfb"/><rect x="315" y="85" width="45" height="45" fill="#d7edfb"/><path d="M228 130V180 M338 130V180 M250 105H315" stroke="#dc493a"/>${txt(60,50,'基準側')}${txt(370,50,'移動側')}${txt(155,75,'ヘッドと受光部')}${txt(200,233,'カップリング')}${txt(45,320,'回転位置・ヘッド間距離・フット位置を入力')}`):svg('トータルステーションまたはレーザートラッカーから目標まで角度と距離を測る',`<circle cx="100" cy="230" r="20" fill="#d7edfb"/><path d="M120 223L435 95 M100 230H500 M435 95V230" stroke-dasharray="6 4"/><circle cx="435" cy="95" r="12" fill="#d7edfb"/>${txt(30,290,'測定器')}${txt(325,66,'プリズム・反射球')}${txt(175,150,'角度＋距離')}${txt(220,270,'座標・三次元位置')}${txt(26,325,'基準座標とターゲット補正を設定する')}`);
const field=(id,label,value)=>`<label>${label}<input id="${id}" type="number" step="any" value="${value}"></label>`;
const result=id=>`<pre id="${id}" class="surveyResult130" role="status" aria-live="polite"></pre>`;
const details=(title,body)=>`<details><summary>${title}</summary>${body}</details>`;
const links=`<p>参考：<a href="https://positioning.topcon.co.jp/jp/document/manual/?dcid=9" target="_blank" rel="noopener">TOPCON：レベル取扱説明書</a> ／ <a href="https://positioning.topcon.co.jp/sokkia/document/manual/?dcid=8" target="_blank" rel="noopener">SOKKIA：セオドライト取扱説明書</a>。図はアプリ用の模式図です。操作つまみ・精度・点検手順は機種の取扱説明書で確認してください。資料確認：2026-10-08。</p>`;
function transitHTML(){return `<h2>🔭 トランシット｜使い方・通り・角度測定</h2><p>機械据付の基準線づくり、ロール・架台の通り、直角方向、鉛直の確認に使います。ここではトランシット／セオドライトをまとめて扱います。基本は<b>望遠鏡で目標を視準して角度や基準線を読む機械</b>です。電子角度表示があっても距離測定機能があるとは限りません。</p>${transitDiagram()}
${details('① 測定できること・他の測定器との違い',`<div class="surveyTable130"><table><thead><tr><th>測定・確認</th><th>使い方と条件</th></tr></thead><tbody><tr><td>水平角・直角</td><td>基準点を0°に設定し、別の点を視準して角度を読む。90°方向の墨を設定する際は据付中心も一致させる。</td></tr><tr><td>通り・平行の比較</td><td>基準直線に対する横方向の差を各測点で読む。差を測点間距離で割ると相対傾きになる。</td></tr><tr><td>鉛直・倒れ</td><td>下と上の中心を同じ鉛直面から見る。直交するもう一方向でも確認して二方向の倒れを分ける。</td></tr><tr><td>仰角・俯角</td><td>鉛直角の表示方式を確認。水平0°の仰俯角と、真上0°の天頂角を混同しない。</td></tr><tr><td>高低差の計算</td><td>角度だけでは不足。水平距離または斜距離、器械高、目標高が必要。</td></tr><tr><td>概略距離</td><td>スタジア線付き機種は標尺を使える。係数K・加数Cを機種で確認する。精密な据付距離測定の代替にはしない。</td></tr></tbody></table></div><p>精密な高低差にはレベル、軸同士の芯出しにはダイヤルゲージや専用レーザー、三次元座標と距離にはトータルステーション等を用途に合わせて使います。基準直線に平行でも、設計位置・高さが一致しているとは限りません。</p>`)}
${details('② 据付から視準までの手順',`<ol><li><b>基準を決める：</b>基準点2点・機械基準面・測点位置・目標値・座標の＋方向を決めて記録。基準線と機械中心線のオフセットも分ける。</li><li><b>三脚：</b>安定した床へ脚を開き、脚頭を概ね水平にする。人・台車の接触、床振動、沈みを避け、本体を確実に固定。</li><li><b>求心：</b>角度を基準点の頂点から測る場合は、垂球・光学求心器等で測点の真上に据える。離れた位置で通りを見る場合は、設定した視準線の位置が重要。</li><li><b>整準：</b>円形気泡で粗合わせ後、管形気泡がある機種は2本の整準ねじに平行な方向と90°回した方向で順に調整。回転後も気泡を再確認。求心と整準を交互に確認する。</li><li><b>十字線のピント：</b>接眼レンズで十字線を鮮明にする。次に合焦つまみで目標を鮮明にする。</li><li><b>視差を消す：</b>目を少し上下左右に動かして、十字線と目標が相対的に動かないことを確認。測距離が変わったら再合焦。</li><li><b>基準方向：</b>基準点Aを正しく視準して水平角の0設定・固定。微動で中心合わせ。目盛の回る向きも確認する。</li><li><b>観測：</b>同じターゲット・同じ基準面で繰り返す。反位でも観測し、値の整合を確認。正位と反位の目盛を単純平均せず、角度差・180°や360°の折返しを扱う機種の手順に従う。</li><li><b>基準へ戻る：</b>最後に基準点をもう一度見て、ずれ・三脚移動を確認する。ずれた場合は途中の値をそのまま採用しない。</li></ol><p>太陽を望遠鏡で直接見ないでください。対象の運転・移動による接触を避けて観測し、調整・マーキングは設備を安全な状態にして実施します。</p>`)}
${details('③ 水平角・直角・鉛直の図解',`${planDiagram()}<p>水平角 β＝B方向の読み − A方向の読み（0～360°へ正規化）。同じ向きで角度差を測ることが条件です。基準方向が0°ならB方向の表示がそのまま角度になります。測角の最小表示と精度は別です。</p><p>90°方向を出すには、Aを基準に水平角90°へ振って目標を設定します。A方向の基準誤差や器械の偏心も移るため、既知基準から再検査します。オートレベルの粗い水平目盛を精密な直角出し用セオドライトと同等には扱いません。</p><p>鉛直確認は、下の中心を縦十字線へ合わせ、望遠鏡だけを上下に振って上の中心を確認します。下から上までの高さ差をH、横ずれをeとすると、倒れ角 α＝atan(e/H)。奥行き方向の倒れは直交する別の方向から観測します。</p>`)}
<h3>④ スケール読みから通り・調整量を計算</h3>${scaleDiagram()}<p><b>同じ平面・同じ目盛り向き</b>のスケールを測点A・Bに固定し、双方とも目盛が増える向きを＋Yとします。視準線は固定。目標値gは、その機械を設計位置に置いたときのスケール読みです。測点ごとに基準面が違う場合はgA・gBを別に設定します。</p><p>機械側の位置誤差 e＝g − r。相対傾き α＝atan((eB − eA)/L)。各点で必要な幾何学的移動量は −e＝r − gです。<b>＋Yへスケール・機械を動かすと、視準線の読みは小さくなります。</b>目盛が逆向き、スケールを裏返す、視準線を動かす場合はこの条件が成立しません。</p><div class="surveyGrid130">${field('surRA130','Aの実測読み rA（mm）',250)}${field('surRB130','Bの実測読み rB（mm）',300)}${field('surGA130','Aの目標読み gA（mm）',250)}${field('surGB130','Bの目標読み gB（mm）',250)}${field('surL130','測点A–B間の距離 L（mm）',2500)}</div><p>入力の初期値は計算例です。器械からの離隔5 mではなく、ここでは<b>測点同士の間隔2,500 mm</b>をLへ入力します。</p><button type="button" id="surLineCalc130">通り・角度を計算</button>${result('surLineResult130')}<p>表示する移動量は測点の幾何学的な位置補正です。フットやジャッキの移動量とは限りません。Aを固定しBだけ合わせる場合はBの目標値・支点位置を検討し、機械全体を平行移動させる場合とは分けてください。安全に少量調整し、固定・締付け後に再測定します。</p>
<h3>⑤ 角度と距離から高低差を計算</h3>${elevationDiagram()}<p>水平距離Dなら ΔH＝D tan α＋i−t。斜距離Sなら D＝S cos α、ΔH＝S sin α＋i−t。B高さ＝A高さ＋ΔH。天頂角Zで表示する機種は α＝90°−Z。ここでは短距離の幾何計算で、地球曲率・大気屈折・器械の補正は含みません。</p><div class="surveyGrid130"><label>距離の種類<select id="surDistanceMode130"><option value="horizontal">水平距離 D</option><option value="slant">斜距離 S</option></select></label><label>角度の表示<select id="surAngleMode130"><option value="elevation">仰俯角 α（水平0°）</option><option value="zenith">天頂角 Z（真上0°）</option></select></label>${field('surDistance130','距離（mm）',5000)}${field('surAngle130','角度（十進度）',2)}${field('surInstrument130','器械高 i（mm）',1500)}${field('surTarget130','目標高 t（mm）',1500)}${field('surBaseHeight130','器械設置点Aの高さ（mm）',10000)}</div><button type="button" id="surTrigCalc130">高低差を計算</button>${result('surTrigResult130')}
<h3>⑥ 度・分・秒の換算</h3><p>十進度＝度＋分/60＋秒/3600。12°30′00″＝12.5°です。12.30°ではありません。1°＝60′、1′＝60″。微小角でずれe≒Lα（αはrad）。厳密な計算はe＝L tan αです。</p><div class="surveyGrid130"><label>符号<select id="surSign130"><option value="1">＋</option><option value="-1">−</option></select></label>${field('surDeg130','度（整数）',0)}${field('surMin130','分（整数）',0)}${field('surSec130','秒',4)}</div><button type="button" id="surDmsCalc130">角度を換算</button>${result('surDmsResult130')}
${details('⑦ スタジア線による概略距離の式',`<p>水平な視準では、標尺上の上・下スタジア線の読み差sに対して D＝K s＋C。Kは乗定数、Cは加定数です。例えば機種資料でK＝100、C＝0と確認できた場合だけ、s＝0.32 mからD＝32 mと計算できます。sとDの単位をそろえてから計算します。</p><p>傾いた視準で鉛直標尺を読む一般的なスタジア式は D＝K s cos²α＋C cos α。標尺の保持方法・器械方式が前提に合う場合だけ適用します。レーザー距離計の実測距離や、テープの斜距離へこの係数をかけないでください。精密据付では別途精度が確認された距離測定を用います。</p>`)}
${details('⑧ 機械据付の実務・失敗を減らす確認',`<ul><li>ロールの通り：基準軸に沿う視準線を設定し、同一の軸端・ターゲット治具で左右端と複数ロールを比較。軸端面が軸中心を表すかは別途確認。</li><li>架台の平行：同じ基準面の手前・奥で偏差を測る。平行度だけでなく、基準線からの設計オフセットも確認。</li><li>距離の取り違え：器械からの距離は誤差影響の検討に、機械の二測点間距離は傾き計算に使う。目的を分ける。</li><li>基準面の段差・治具厚み：段差があるのに同じ読みを目標にすると、機械を誤って傾ける。ターゲットの取付寸法を反映。</li><li>読取誤差：視差、熱で揺れる像、暗さ、スケール傾き、目盛の向き、反位の扱いを確認。</li><li>締付け後：アンカーボルト、シム、配管接続で移動する場合がある。作業完了状態で基準を再視準し、同じ測点を再測定。</li></ul><p>記録する項目：器械型式・校正日・基準点・測点位置・距離・目盛の向き・目標値・読み・正反観測・締付け状態・気温・再確認結果。角度の表示桁が細かくても、その桁までの据付精度を保証するわけではありません。</p>`)}${links}`;}
function levelHTML(){return `<h2>📏 Yレベル・光学レベル｜高さ・水準測定</h2><p>ベース・架台・基礎など離れた点の高さを、水平な視準線と標尺（スタッフ）の読みで比較します。<b>Yレベルという呼び方だけでは型式を特定できないため</b>、Y型等の手動式水準器、チルチングレベル、自動補正式オートレベルを区別して説明します。手元の器械の名称とつまみを取扱説明書で確認してください。</p>${levelDiagram()}
${details('① Y型・チルチング・オート・デジタルの違い',`<div class="surveyTable130"><table><thead><tr><th>形式</th><th>水平を作る方法・使い方</th></tr></thead><tbody><tr><td>Y型レベル等の手動式</td><td>Y字形支持部などの望遠鏡支持構造をもつ古典的な形式。管形気泡を使い視準線を水平に調整。保持・反転・調整機構は型式ごとに異なる。</td></tr><tr><td>チルチングレベル</td><td>概ね整準した後、各観測で傾斜微動ねじを使い精密気泡を一致させて読む。自動補正があると決めつけない。</td></tr><tr><td>オートレベル</td><td>円形気泡で補正範囲内へ整準すると、補正機構が視準線の小さな傾きを補正する。三脚の大きな傾きや振動は補正できない。</td></tr><tr><td>デジタルレベル</td><td>対応するバーコード標尺を読み取る機種。標尺の規格・照明・距離・読取条件を確認。全ての普通標尺を電子読取りできるわけではない。</td></tr><tr><td>精密平形水準器</td><td>機械の面に直接置いて傾きを測る器具。標尺を遠方から見るレベルとは測定方法が異なる。</td></tr></tbody></table></div><p>水準器の感度がmm/m表示なら、高さ差＝感度×気泡移動目盛数×測定長さ(m)。感度の表示が「1目盛当たり」か別の定義かを器械で確認します。離れた機械点の高さは、通常はレベル＋標尺で比較します。</p>`)}
${details('② 使い方：据付・ピント・読取り',`<ol><li><b>基準点：</b>動かない基準点Aの高さを決める。絶対標高が不要な据付では、例えばA＝10,000 mmという仮の高さでもよい。途中で基準を変更しない。</li><li><b>据付：</b>AとBまでの視準距離がなるべく等しくなる位置へ三脚を立て、本体を固定。点の真上に求心するより、距離の釣合いを重視する測定。</li><li><b>整準：</b>手動式は精密気泡を機種手順で合わせ、観測中も確認。チルチング式は視準ごとに気泡合わせ。オート式は円形気泡を中心へ導き、補正の安定を待つ。</li><li><b>視差：</b>接眼レンズで十字線、合焦つまみで標尺を鮮明にする。目を動かして十字線と目盛がずれないことを確認。</li><li><b>標尺：</b>ゼロ位置・接地点を確認して鉛直に保持。標尺用気泡や治具を使う。斜めに立てた標尺の読みは一般に大きくなる。</li><li><b>後視BS：</b>基準点Aに置いた標尺の中央横線の読みを記録。器械位置・高さを変えず、測りたい点Bの前視FSを読む。</li><li><b>計算：</b>Bの高さ＝Aの高さ＋BS−FS。読みが小さい点ほど、同じ視準線の下では高い。</li><li><b>再確認：</b>Aへ戻って読みを再確認。三脚・標尺の足元・測点が動いていれば、基準から取り直す。</li></ol><p>標尺目盛をmで読む場合でも、この計算欄ではmmに換算します。1.500 m＝1,500 mm。ベース上に小さなスケールを使う場合は、スケールのゼロが測定面からどれだけ浮いているか、治具高さが同じかを確認してください。逆さ標尺はこの入力方式の対象外です。</p>`)}
<h3>③ 同じ据付位置から複数点の高さを計算</h3><p>視準線の高さ HI＝基準点高さHA＋BS。各点高さ＝HI−FS。調整量＝目標高さ−各点高さ。＋なら高さを上げ、−なら下げる方向です。ここで計算するのは<b>測点の高さ補正</b>で、支持構造を考慮したジャッキ・シム量ではありません。</p><div class="surveyGrid130">${field('levBase130','基準点Aの高さ HA（mm）',10000)}${field('levBS130','基準点の後視 BS（mm）',1500)}${field('levTarget130','全測点の目標高さ（mm）',10000)}</div><label>測点名, 前視FS（mm）を1行1点で入力（例）<textarea id="levPoints130" rows="5">B,900
C,1100
D,1500</textarea></label><button type="button" id="levCalc130">測点の高さを計算</button>${result('levResult130')}<p>最大50点。同じ器械据付・同じ後視で読んだ点だけを入れます。器械を移動したら、移動前に前視を読んだ不動の転点を次の後視点にして、別の計算としてつなげてください。入力値は計算例です。</p>
${details('④ 器械を移動する場合・閉合確認',`<p>据付1：HA＋BS1−FS1＝転点TPの高さ。据付2：HTP＋BS2−FS2＝次の点の高さ。複数据付の全高低差は ΣBS−ΣFSです。中間点の読みを全てFSの総和へ加えると誤計算になります。移動のつなぎに使った各転点の前視・後視を集計してください。</p><p>既知の高さへ戻る閉合測定では f＝測定で求めた終点高さ−既知終点高さ。許容値は距離・等級・設備仕様・測定計画から決め、画面の表示桁で判断しません。往復観測や基準点の再読取りで再現性を確認します。</p><p>機械の4フットを比較する場合は、取付面・治具厚さをそろえて各点を読みます。ベースを傾けないための相対高さと、設備全体の設計高さを別に管理します。締付け前後やモーター接続前後も同じ条件で記録します。</p>`)}
<h3>⑤ 二点法：視準線の傾きが疑われる場合</h3>${pegDiagram()}<p>AとBの<b>等距離の中間</b>から両方を読んで真の高低差の近似を求め、次にA寄りから同じ2点を読みます。等距離では距離に比例する視準線の傾きの影響が相殺されますが、標尺の傾き・基準点の移動など全ての誤差が消えるわけではありません。</p><div class="surveyGrid130">${field('pegMA130','中間据え：Aの読み（mm）',1500)}${field('pegMB130','中間据え：Bの読み（mm）',1400)}${field('pegNA130','A寄り：Aの読み（mm）',1200)}${field('pegNB130','A寄り：Bの読み（mm）',1100.2)}${field('pegDA130','A寄りの器械からAまで（mm）',2000)}${field('pegDB130','A寄りの器械からBまで（mm）',30000)}</div><button type="button" id="pegCalc130">読取り差を確認</button>${result('pegResult130')}<p>表示は幾何学的な確認値で、校正証明や合否判定ではありません。距離・標尺保持・読みの再現性を再確認し、差が残る場合は型式の点検手順・メーカー点検へ。精密調整ねじをこの計算だけで回さないでください。</p>
${details('⑥ ありがちな誤差・点検・保管',`<ul><li>読みがふらつく：三脚の緩み、床振動、補正機構が安定していない、陽炎、標尺の保持を確認。</li><li>回すと気泡がずれる：円形・管形気泡と整準の状態を確認。器械を逆方向に回しても確認。</li><li>高さがつながらない：BSとFSの取り違え、単位、転点移動、標尺の底・継ぎ目、据付移動後のHI更新漏れ。</li><li>測距離で結果が変わる：視準線の傾きと距離の不釣合いを確認。可能な範囲で等距離にする。</li><li>機械への治具：磁石や押付け力でスケールが傾いていないか、異なる治具のゼロ位置が一致しているか確認。</li><li>使用後：汚れ・湿気を除き、機種の格納手順でケースへ。落下・衝撃後は測定前に点検する。</li></ul><p>一般的なレベルは工事向けの標尺読取りが目的です。サブミリの機械高さ調整では、器械・標尺・治具・距離・環境を含む精度確認が必要です。長い距離や熱源の上を通る視準は、大気の影響も考慮します。</p>`)}${links}`;}
const laserTypes=[
['distance','レーザー距離計','長さ・連続距離、対応機種では面積・体積・間接高さ。','測定基準を前端・後端・三脚ねじなどから確認 → 安定して保持 → 対象面へ照射 → 複数回測って比較。','斜めに狙うと斜距離になります。ガラス・鏡・磨いた金属・暗い面・日光では誤反射や読取り不安定があり、指定ターゲット板等を用います。','機械間の概略離隔・建屋寸法。精密な軸芯出しや真直度を距離計だけで決めない。'],
['line','レーザー墨出し器・ラインレーザー','水平・鉛直の基準ライン、機種によって直角ライン。','安定設置 → ロック解除・自動整準を確認 → 基準墨へ合わせる → 線の中心を読んでマーキング → 基準を再確認。','傾斜・手動モードの線は水平とは限りません。厚いレーザー線の端を読むとずれます。受光器は波長・パルス方式・対応機種を合わせます。','基礎・架台・配管支持の基準線づくり。直角機能の有無と点検方法を確認。'],
['rotary','回転レーザー・ローテーティングレーザー','広い範囲に水平面を作り、受光器とロッドで高低差を比較。勾配設定は対応機種のみ。','三脚へ固定 → 自動整準の安定 → 受光器をロッドへ固定 → 基準点で読み → 各点で同じ受光器の中心を捉えて読む。','受光器の粗・精モードを区別。勾配設定や整準範囲外のまま使用しない。衝撃警報後は基準点から再確認。','基礎天端・長いライン周辺の高さ比較。精密ベースの最終調整には必要精度との適合を確認。'],
['plumb','ポイントレーザー・鉛直レーザー','上下点で鉛直位置の転写、機種によって直角方向の点。','床の基準点へ下点を合わせる → 整準・鉛直点を確認 → 上点を天井などへ転写 → 点の中心を記録。','鉛直転写と距離・高さの数値測定は別の機能。設置面の移動や高さに対する角度誤差を確認。','柱・機械中心線の転写、上下の位置合わせ。'],
['coordinates','トータルステーション','角度と距離から座標・高低差、既知座標からの位置出し。','既知点へ求心・整準 → 器械高入力 → 後視で座標の向きを設定 → 目標高とプリズム定数等を確認 → 観測・既知点で検査。','プリズム・ノンプリズムのモードと測定対象を区別。基準座標や後視が誤ると、見かけ上は整った座標でも設備位置が誤る。','長いラインの設備基準点・レイアウト。採用する測距方式は型式による。'],
['tracker','レーザートラッカー','反射球等の三次元座標。大型機械の位置・形状比較。','安定設置・暖機等の手順 → ターゲットの設定と器械点検 → 複数の基準点で座標系を定義 → 測点を取得 → 既知点へ戻って確認。','反射球中心と接触点の半径補正、遮光、座標合わせ、温度・気圧などの補正を確認。一般の距離計とは別の専用システム。','大型架台・ロールライン・組立の三次元測定。機種ごとの測定不確かさと必要精度を評価。'],
['shaft','レーザー軸芯出し器','回転軸同士のオフセット・角度ずれ、フット位置での調整量。','設備停止・不用意な起動を防止 → 取付ヘッドと寸法入力 → ソフトフット・取付の緩み確認 → 指定回転位置で観測 → 補正 → 締付け後再測定。','測定ヘッドの取付、フット距離、基準側と移動側、熱成長目標を確認。移動方向は装置画面と実機の向きを照合。','モーター・減速機・ポンプの芯出し。建築用ラインレーザーを代用しない。']
];
function laserHTML(){return `<h2>🔴 レーザー測定器｜種類・使い方・図解</h2><p>「レーザー」という名前が同じでも、距離を測るもの、基準線を出すもの、軸ずれや三次元座標を測るものは別です。作業に必要な<b>測定量・距離・許容差・環境</b>から使い分けます。</p><label>種類・用途を検索<input id="laserSearch130" type="search" placeholder="例：芯出し、距離、回転、座標"></label><button type="button" id="laserClear130">検索をクリア</button><p id="laserCount130" role="status" aria-live="polite"></p><div id="laserCards130">${laserTypes.map(([id,name,measure,steps,care,use])=>details(name,`${laserDiagram(id)}<p><b>測定できること：</b>${measure}</p><p><b>使い方：</b>${steps}</p><p><b>測定条件：</b>${care}</p><p><b>機械据付での用途：</b>${use}</p>`)).join('')}</div><p id="laserEmpty130" hidden>該当する種類がありません。検索をクリアしてください。</p>
<h3>斜距離と角度から水平距離・高さを換算</h3>${elevationDiagram()}<p>D＝S cos α、v＝S sin α。αは水平からの角度で、上向きを＋、下向きを−にします。角度機能のない距離計はαを自動測定できません。<b>vは測定基準位置と照射点の高低差</b>で、床からの高さや機械の高さを直接表すとは限りません。</p><div class="surveyGrid130">${field('laserS130','斜距離 S（mm）',5000)}${field('laserA130','水平からの角度 α（十進度）',30)}</div><button type="button" id="laserCalc130">水平距離・高低差を計算</button>${result('laserResult130')}
${details('精度の見方・使う前の確認',`<p>表示の最小桁、繰返し精度、測定精度、校正結果は別です。例えば表示が0.1 mmでも、装置の距離測定精度が0.1 mmとは限りません。メーカー仕様の距離・反射条件・気温・照明条件を確認します。</p><p>角度誤差δθの横ずれは e＝L tan δθ。仮に10秒の角度誤差がある場合、5,000 mm先では約0.242 mmのずれになります。これは幾何学的な説明例で、特定機種の精度ではありません。距離が長いほど角度誤差の影響は増えます。</p><ol><li>距離計：測定基準面・単位・ターゲット面を確認し、既知距離で繰り返し比較。</li><li>ライン・回転・ポイント機：機種の取扱説明書にある壁面・回転・反転等の精度チェックを実施。見やすさだけで採用しない。</li><li>受光器：中心位置・読取りモード・固定状態を記録。対応機種を使用。</li><li>座標・芯出し機：基準系・入力寸法・ターゲット補正を確認。取付・再測定の再現性を検査。</li><li>完了時：基準点や既知距離へ戻り、途中の移動・熱変化・衝撃の影響を確認。</li></ol><p>レーザーを人の目に向けたり、ビームをのぞいたりしないでください。反射面からの光と周囲の人も確認し、レーザークラスに応じた機種の取扱手順を守ります。緑色で見やすくても測定精度が高いと決まるわけではありません。</p>`)}
${details('出典・対応範囲',`<p>説明・計算は手動入力を支援する学習用です。このアプリから測定器を接続・制御したり、自動で実測値を取得したりする機能はありません。出典リンク以外はアプリ内で使えます。</p><ul><li><a href="https://www.bosch-professional.jp/jp/ja/products/glm-400-0601072R50" target="_blank" rel="noopener">Bosch：レーザー距離計・取扱説明書</a></li><li><a href="https://jpn.tajimatool.co.jp/page/owner_manual3" target="_blank" rel="noopener">TAJIMA：レーザー墨出し器・受光器の説明書</a> ／ <a href="https://jpn.tajimatool.co.jp/page/lasermarking_warnings" target="_blank" rel="noopener">使用前後の点検案内</a></li><li><a href="https://leica-geosystems.com/ja-jp/products/total-stations" target="_blank" rel="noopener">Leica：トータルステーション</a> ／ <a href="https://leica-geosystems.com/ja-jp/products/laser-tracker-systems" target="_blank" rel="noopener">レーザートラッカー</a></li><li><a href="https://www.skf.com/binaries/pub12/Images/0901d1968044c54f-11443EN_ShaftAlignmentTools_tcm_12-263547.pdf" target="_blank" rel="noopener">SKF：軸芯出し器の構成・測定方式</a></li></ul><p>資料確認：2026-10-08。図は方式を説明する模式図です。製品の形状・数値仕様・操作は手元の型式の説明書を確認してください。</p>`)} `;}
document.addEventListener('DOMContentLoaded',()=>{
const sections={};for(const [id,html] of [['transit130',transitHTML()],['level130',levelHTML()],['laser130',laserHTML()]]){const s=document.createElement('section');s.id=id;s.className='card survey130';s.innerHTML=html;(document.getElementById('material60')||document.body.lastElementChild).before(s);sections[id]=s;}
const $=id=>document.getElementById(id);
const n=id=>{const raw=$(id).value.trim();if(raw==='')throw Error('未入力の欄があります。');const v=Number(raw);if(!Number.isFinite(v))throw Error('数値を入力してください。');return v;};
function bind(sectionId,buttonId,resultId,compute){$(buttonId).addEventListener('click',()=>{try{$(resultId).textContent=compute()}catch(e){$(resultId).textContent='入力を確認：'+e.message}});sections[sectionId].querySelectorAll('input,select,textarea').forEach(el=>{for(const ev of ['input','change'])el.addEventListener(ev,()=>{$(resultId).textContent=''})});}
bind('transit130','surLineCalc130','surLineResult130',()=>{const x=line(n('surRA130'),n('surRB130'),n('surGA130'),n('surGB130'),n('surL130'));return `機械の位置偏差（＋Y方向が正）\nA：${fmt(x.eA)} mm / B：${fmt(x.eB)} mm\nB−A：${fmt(x.delta)} mm\n相対傾き：${fmt(x.angle,6)}°（${fmt(x.angle*3600,2)}秒）\n勾配：${fmt(x.slope)} mm/m\n目標位置への測点補正\nA：${fmt(x.moveA)} mm / B：${fmt(x.moveB)} mm\n＋は両スケールの目盛が増える向き。\nフットやジャッキの調整量ではありません。`;});
bind('transit130','surTrigCalc130','surTrigResult130',()=>{const x=trig(n('surDistance130'),n('surAngle130'),$('surDistanceMode130').value,$('surAngleMode130').value,n('surInstrument130'),n('surTarget130'),n('surBaseHeight130'));return `水平からの角度 α：${fmt(x.a,6)}°\n水平距離 D：${fmt(x.D)} mm\n視準線の高さ変化：${fmt(x.v)} mm\nB−Aの高低差：${fmt(x.dh)} mm\nBの高さ：${fmt(x.height)} mm（${fmt(x.height/1000,6)} m）`;});
bind('transit130','surDmsCalc130','surDmsResult130',()=>{const x=dms(n('surDeg130'),n('surMin130'),n('surSec130'),n('surSign130'));return `十進度：${fmt(x.angle,9)}°\nラジアン：${fmt(x.radian,12)} rad\n1 m先の幾何学的ずれ：${fmt(x.perM,6)} mm\n器械の精度や合否判定ではありません。`;});
bind('level130','levCalc130','levResult130',()=>{const raw=$('levPoints130').value.trim();if(!raw)throw Error('測点を入力してください。');const pts=raw.split(/\r?\n/).map(row=>{const cells=row.replace(/，/g,',').split(',');if(cells.length!==2||!cells[0].trim()||!cells[1].trim())throw Error('各行は「測点名, 前視の数値」で入力してください。');return {name:cells[0].trim(),fs:Number(cells[1])}});const x=level(n('levBase130'),n('levBS130'),pts,n('levTarget130'));return `視準線の高さ HI：${fmt(x.hi)} mm\n`+x.points.map(p=>`${p.name}：前視 ${fmt(p.fs)} mm\n  高さ ${fmt(p.height)} mm / 基準点との差 ${fmt(p.dh)} mm\n  目標への高さ補正 ${fmt(p.move)} mm\n  目標位置での標尺読み ${fmt(p.targetReading)} mm`).join('\n')+'\n＋は高さを上げ、−は下げる。負の目標読みは通常の正立標尺では視準線の下から読めない条件です。';});
bind('level130','pegCalc130','pegResult130',()=>{const x=peg(n('pegMA130'),n('pegMB130'),n('pegNA130'),n('pegNB130'),n('pegDA130'),n('pegDB130'));return `中間据えによるB−A：${fmt(x.dh)} mm\nA寄り観測のB期待値：${fmt(x.expectedB)} mm\nB実測−期待値：${fmt(x.discrepancy)} mm\n推定の視準線勾配影響：${fmt(x.per10m)} mm / 10 m\n符号は距離が増える向きの読みへの影響です。\n点検用の参考計算。自動校正・合否判定ではありません。`;});
bind('laser130','laserCalc130','laserResult130',()=>{const x=project(n('laserS130'),n('laserA130'));return `水平距離 D：${fmt(x.D)} mm\n照射点−測定基準位置の高低差：${fmt(x.v)} mm\n床や機械の高さは、測定基準位置との関係を別途確認。`;});
const normalize=s=>s.normalize('NFKC').toLowerCase().replace(/\s+/g,'');function search(){const q=normalize($('laserSearch130').value);let count=0;sections.laser130.querySelectorAll('#laserCards130 > details').forEach((el,i)=>{const keep=normalize(laserTypes[i].join(' ')).includes(q);el.hidden=!keep;if(keep)count++;});$('laserCount130').textContent=`${count}種類 / 全${laserTypes.length}種類`;$('laserEmpty130').hidden=count>0;}$('laserSearch130').addEventListener('input',search);$('laserClear130').addEventListener('click',()=>{$('laserSearch130').value='';search();$('laserSearch130').focus()});search();
});
})();
