/* Drawing-assisted manual mass estimate. No OCR or external image transfer. */
(()=>{'use strict';
const SHAPES={box:['角板・角柱',['幅','高さ','長さ'],v=>v[0]*v[1]*v[2],'幅×高さ×長さ'],cylinder:['丸棒・円柱・丸穴',['直径','長さ／深さ'],v=>Math.PI*v[0]**2*v[1]/4,'π×直径²×長さ÷4'],tube:['中空円筒・リング',['外径','内径','長さ'],v=>Math.PI*(v[0]**2-v[1]**2)*v[2]/4,'π×(外径²−内径²)×長さ÷4'],frustum:['円すい台・円すい',['大径','小径（円すいは0）','高さ'],v=>Math.PI*v[2]*(v[0]**2+v[0]*v[1]+v[1]**2)/12,'π×高さ×(大径²＋大径×小径＋小径²)÷12'],triangle:['三角柱・直線面取り',['底辺','三角形の高さ','長さ'],v=>v[0]*v[1]*v[2]/2,'底辺×高さ×長さ÷2']};
function volume(shape,values,count){if(!SHAPES[shape])throw Error('形状を選んでください');if(!Number.isInteger(count)||count<1)throw Error('個数は1以上の整数');if(values.length!==SHAPES[shape][1].length||values.some((n,i)=>!Number.isFinite(n)||(shape==='frustum'&&i===1?n<0:n<=0)))throw Error('寸法は正の数で入力（円すいの小径のみ0可）');if((shape==='tube'||shape==='frustum')&&values[0]<=values[1])throw Error('外径／大径は内径／小径より大きくしてください');const v=SHAPES[shape][2](values)*count;if(!Number.isFinite(v))throw Error('値が大きすぎます');return v}
window.massMath124={volume,mass:(v,d)=>{if(!Number.isFinite(d)||d<=0)throw Error('密度は正の数');return v*d/1e6}};
const E=(t,s)=>{const e=document.createElement(t);if(s)e.textContent=s;return e};
function input(type,value){const i=E('input');i.type=type;i.value=value;if(type==='number'){i.step='any';i.inputMode='decimal'}return i}
function label(s,i){const l=E('label',s);l.append(i);return l}
function button(s,fn){const b=E('button',s);b.type='button';b.addEventListener('click',fn);return b}
function select(options){const s=E('select');for(const [v,t]of options){const o=E('option',t);o.value=v;s.append(o)}return s}
document.addEventListener('DOMContentLoaded',()=>{
const section=E('section');section.id='drawingMass124';section.className='card mass124';section.append(E('h2','📷 図面写真を見ながら重量計算'),E('p','写真の寸法・材質を確認して入力する方式です。自動読取りではありません。外形の体積を足し、穴・溝を引き、密度から概算重量（質量kg）を求めます。寸法はすべてmm。'));
const photos=E('details');photos.open=true;photos.append(E('summary','① 図面写真を選択・拡大'));const file=input('file','');file.accept='image/*';file.multiple=true;const photoStatus=E('p');photoStatus.setAttribute('aria-live','polite');const gallery=E('div');photos.append(label('写真を選ぶ（複数可）',file),photoStatus,gallery);section.append(photos);const urls=new Set();
file.addEventListener('change',()=>{for(const url of urls)URL.revokeObjectURL(url);urls.clear();gallery.replaceChildren();photoStatus.textContent='';for(const f of Array.from(file.files||[]).slice(0,6)){const card=E('div'),viewport=E('div'),img=E('img');viewport.className='massPhoto124';img.alt='参照図面：'+f.name;const url=URL.createObjectURL(f);urls.add(url);img.src=url;img.addEventListener('error',()=>{photoStatus.textContent='表示できない写真があります。JPEG・PNGまたはスクリーンショットで選び直してください。'});viewport.append(img);const zoom=input('range','100');zoom.min=100;zoom.max=400;zoom.step=25;zoom.addEventListener('input',()=>{img.style.width=zoom.value+'%';img.style.maxWidth='none'});card.append(E('p',f.name),label('拡大率（左右・上下にスクロールできます）',zoom),viewport);gallery.append(card)}if((file.files||[]).length>6)photoStatus.textContent='先頭6枚を表示しました。';});
photos.append(E('p','写真はこの画面で参照するだけで外部送信しません。写真は再読込すると消えます。入力結果は下の計算メモから保存できます。'));
const part=input('text',''),material=input('text',''),density=input('number','7.85');density.min='0';const preset=select([['7.85','一般的な鋼：7.85 g/cm³（概算）'],['2.7','アルミ：2.70 g/cm³（概算）'],['custom','密度を手入力']]);preset.addEventListener('change',()=>{if(preset.value!=='custom')density.value=preset.value;invalidate()});density.addEventListener('input',()=>{preset.value='custom';invalidate()});
section.append(E('h3','② 部品名・材質・密度'),label('部品名／図番',part),label('図面に記載された材質',material),label('密度の参考値',preset),label('計算に使う密度 g/cm³',density),E('p','鋼・アルミは代表値です。ステンレス、鋳鉄、銅合金などは材料仕様の密度を入力してください。この計算は一つの密度の部品用です。異材組立は材質ごとに計算します。'));
const rowList=E('div');let rows=[];const result=E('div');result.className='massResult124';result.setAttribute('aria-live','polite');const memo=E('textarea');memo.readOnly=true;memo.rows=10;let last='';
function invalidate(){last='';result.textContent='入力を確認して「重量を計算」を押してください。';memo.value=''}
function addRow(initial={}){const card=E('article');card.className='massRow124';const name=input('text',initial.name||''),sign=select([['1','＋ 外形を足す'],['-1','− 穴・溝を引く']]),shape=select(Object.entries(SHAPES).map(([k,v])=>[k,v[0]])),count=input('number',initial.count||1);count.step='1';count.min='1';sign.value=initial.sign||'1';shape.value=initial.shape||'box';const dims=E('div');let fields=[];const row={card,name,sign,shape,count,get fields(){return fields}};function render(values=[]){dims.replaceChildren();fields=SHAPES[shape.value][1].map((n,i)=>{const x=input('number',values[i]??'');x.addEventListener('input',invalidate);dims.append(label(n+' mm',x));return x});invalidate()}
shape.addEventListener('change',()=>render());[name,sign,count].forEach(x=>x.addEventListener('input',invalidate));card.append(label('部分名（例：外形、中央穴）',name),label('足す／引く',sign),label('形状',shape),dims,label('同じ形状の個数',count),button('この部分を削除',()=>{card.remove();rows=rows.filter(r=>r!==row);invalidate()}));rowList.append(card);rows.push(row);render(initial.values)}
section.append(E('h3','③ 形状を分けて追加'),E('p','段付き軸は重ならない円柱に分けます。穴は「引く」で追加。座ぐりは貫通穴と重なる体積を二重に引かないよう、段の部分をリングで引く方法があります。重なり・穴の位置は自動判定しません。'),rowList,button('＋ 部分を追加',()=>addRow()));
section.append(button('計算例を追加：板＋4穴',()=>{addRow({name:'例：板（他の行と合算されます）',shape:'box',values:[200,100,10]});addRow({name:'例：直径10の貫通穴4個',sign:'-1',shape:'cylinder',values:[10,10],count:4})}));
section.append(button('重量を計算',()=>{try{if(!rows.length)throw Error('形状を1つ以上追加してください');const d=Number(density.value);if(!density.value.trim()||!Number.isFinite(d)||d<=0)throw Error('密度を正しく入力してください');let total=0,plus=0,minus=0;const lines=[];rows.forEach((r,i)=>{let v;try{v=volume(r.shape.value,r.fields.map(f=>f.value.trim()===''?NaN:Number(f.value)),Number(r.count.value))}catch(e){throw Error('部分'+(i+1)+'：'+e.message)}const neg=r.sign.value==='-1';total+=neg?-v:v;if(neg)minus+=v;else plus+=v;lines.push(`${i+1}. ${r.name.value||SHAPES[r.shape.value][0]}：${neg?'−':'＋'}${v.toFixed(2)} mm³\n  ${SHAPES[r.shape.value][1].map((n,j)=>n+'='+r.fields[j].value+'mm').join('、')}、個数=${r.count.value}\n  式：${SHAPES[r.shape.value][3]}`)});if(!Number.isFinite(total)||total<=0)throw Error('残る体積が0以下、または計算範囲外です。外形と除去量を確認してください');const mass=window.massMath124.mass(total,d);if(!Number.isFinite(mass))throw Error('計算範囲外です');result.textContent='概算重量 '+mass.toLocaleString('ja-JP',{maximumSignificantDigits:7})+' kg（理論質量）';last=`図面からの重量計算（手入力による概算）\n部品：${part.value}\n材質：${material.value||'未記入'}\n密度：${d} g/cm³\n\n${lines.join('\n')}\n\n外形合計：${plus.toFixed(2)} mm³\n除去合計：${minus.toFixed(2)} mm³\n正味体積：${total.toFixed(2)} mm³\n重量＝体積×密度÷1,000,000\n概算重量：${mass.toPrecision(7)} kg\n\n形状の重なり、未入力の穴・溝・ねじ・面取り、寸法公差、密度差、付属物は自動補正していません。吊り具選定には実重量・重心などを別途確認。`;memo.value=last}catch(e){invalidate();result.textContent='計算できません：'+e.message}}),result,label('④ 計算メモ（長押しでコピーも可能）',memo),button('計算メモを保存',()=>{if(!last){result.textContent='先に重量を計算してください。';return}const url=URL.createObjectURL(new Blob([last],{type:'text/plain;charset=utf-8'}));const a=E('a');a.href=url;a.download='weight-calculation.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}),E('p','理論体積からの概算です。ねじ・小穴・面取りを省略した場合や密度が代表値の場合は、その分の誤差があります。吊り作業では、この値だけで吊り具を選定せず実重量・重心・付属物を確認してください。'));
[part,material].forEach(x=>x.addEventListener('input',invalidate));
const refs=E('p');refs.innerHTML='<a href="https://www.nipponsteel.com/product/sheet/catalog/" target="_blank" rel="noopener">日本製鉄：鋼板カタログ</a> ／ <a href="https://www.kobelco.co.jp/products/advanced-materials/about-almi/characteristic.html" target="_blank" rel="noopener">神戸製鋼：アルミの特性</a>';section.append(refs);addRow();document.getElementById('material60').before(section);
});
})();
